src/commands/play.ts, src/commands/skip.ts, src/commands/stop.ts, src/kmq.ts, src/models/game_session.ts
- Don't need to update on `,end` since GameSession gets destroyed anyway
- Now we only process guesses when game is in session, not processing when game is stopped
Closes #198
=> Update activity timestamp on `,play`, `,stop`, `,skip`, and guess [#198]

src/commands/limit.ts
This check was originally used to fix the `,options` message to prevent cases like "Now playing 500 out of 200 songs." The `,options` message now has proper logic to show this correctly, without modifying the internal guild preference limit. This will prevent unintended limit changes 
Closes #215
=> No longer hardcap limit based on number of filtered songs [#215]

package-lock.json, src/commands/play.ts, src/commands/skip.ts, src/commands/stop.ts, src/helpers/game_utils.ts, src/kmq.ts, src/models/game_session.ts
Increasing delay between `voiceConnection.play()` calls resets every time we re-join the voice connection. GameSession automatically leaves and rejoins the channel every 15 seconds as a workaround.
=> Workaround for bug where delay between songs continuously increased

src/models/game_session.ts
Prevent re-encoding songs when playing back with ffmpeg by using opus format with `-c copy` encoder option
=> Switch from mp3 files to ogg

src/helpers/game_utils.ts, src/scripts/download-new-songs.ts, src/seed/create_available_songs_table.sql, src/seed/seed_db.ts
Store `available_songs` in `kmq` database so it doesn't get deleted upon seed. Use temporary table and atomic swap to ensure no downtime
Closes #348
=> Recreate available songs table in a transaction

src/scripts/store-daily-stats.ts
I was comparing the date, but forgot to take into account that it'll also compare the time portion of the date. Thus, new players weren't correctly being counted.
=> Correctly compare first_play in store-daily-stats

src/structures/game_session.ts
endRound sends the endOfRoundMessage, which relies on an updated scoreboard to show the correct scores
=> Move updateScoreboard before endRound

src/scripts/download-new-songs.ts, src/seed/bootstrap.ts, src/seed/seed_db.ts
- Fix bug where calling `downloadNewSongs` with limit did not populate `not_downloaded` table correctly
- Add `limit` option to our `npm run seed` script
- Fix bug where `CreateAvailableSongsTable` procedure was being called before `kmq` table was created
=> Fix seed scripts

src/helpers/game_utils.ts
`joinVoiceChannel()` is a no-op if already in a voice channel, but handles re-connection if the connection disconnects
=> Always call joinVoiceChannel

.eslintrc.json, package.json, sql/create_kmq_data_tables_procedure.sql, src/config/knexfile_agnostic.js, src/config/knexfile_kmq.js, src/config/knexfile_kmq_test.js, src/config/knexfile_kpop_videos.js, src/config/knexfile_kpop_videos_validation.js, src/database_context.ts, src/scripts/backup-kmq-database.ts, src/scripts/download-new-songs.ts, src/seed/bootstrap.ts, src/seed/seed_db.ts, yarn.lock
No way of avoiding it for `npm run import`, removed the script. Infrequently used, can be done manually when needed.
=> Avoid exposing db credentials via exec

.github/workflows/docker_build.yml
Scheduled E2E workflow already builds docker image
=> Remove scheduled docker build GH workflow

src/migrations/20210518215005_remove_guild_preference_json.js
Absolute path with spaces can cause issues if there is a space in the path
=> Fix shell-command-injection-from-environment vulnerability in preset migration script call

src/helpers/discord_utils.ts, src/structures/game_session.ts
If the user ,end's during error playing song error, this delay may prevent rounds played being decremented since endSession will likely finish before sendInfoMessage's await, preventing the off by one error. There is a high chance this won't fix the bug.
This commit also adds a newline in between the correct description and youtube link/unique songs counter.
=> Delay rounds played decrement to after song message on round error

src/commands/game_commands/begin.ts, src/commands/game_commands/hint.ts, src/commands/game_commands/play.ts, src/events/client/messageCreate.ts, src/helpers/discord_utils.ts, src/structures/elimination_player.ts, src/structures/elimination_scoreboard.ts, src/structures/game_session.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/team.ts, src/structures/team_scoreboard.ts, src/test/ci/elimination_player.test.ts, src/test/ci/team_scoreboard.test.ts
* Raise scoreboard player capacity from 15 to 30
* Refactor OOP design of elimination and teams scoreboard
* Set maximum lives to 10000
* Mention "The bot prefix" instead of "Your bot prefix"
* Updated formatting for hint and level up message
=> Add support for larger scoreboard, refactor scoreboard OOP

src/commands/admin/stats.ts
Summing an aggregated column of 0 rows returns null for whatever reason
=> Add default value to game round stats

package.json, src/scripts/backup-kmq-database.ts, yarn.lock
Improves backup time from 23s -> 2s locally, decreases output file size from 150MB to 38MB, and speeds up import time significantly.
=> Use mysqldump binary instead of module

src/commands/game_commands/leaderboard.ts, src/helpers/management_utils.ts
* Fix off-by-one error on pages when only 1 page
* Raise reset delay from 1s to 5s after midnight
* Only send temp leaderboard from master
=> Various temporary leaderboard fixes

src/structures/game_session.ts
Uncaught exception: Error 1006 occurs when the VC's underlying websocket abnormally closes. The exception is emited as an error event on the VC object. There is a race condition where if we do `this.connection.removeAllListeners();` before the error event is fired, it will trigger an uncaught exception. 
This approach replaces the listeners with no-ops to 'handle' the exceptions. 
```
26 2021-11-05T07:53:57.620Z [ERROR] - Cluster 1 | uncaughtException | Cluster Uncaught Exception. Reason: Error: 1006: . Trace: Error: 1006:
25 ┊   at WebSocket.<anonymous> (/home/kmq/prod/node_modules/eris/lib/voice/VoiceConnection.js:348:55)
24 ┊   at WebSocket.emit (events.js:315:20)
23 ┊   at WebSocket.emitClose (/home/kmq/prod/node_modules/ws/lib/websocket.js:243:10)
22 ┊   at Receiver.receiverOnFinish …
```
=> Replace VC listeners with no-op instead of blindly removing all listeners

src/test/ci/exp.test.ts
Game round bonus modifier is randomly set to higher value with low probability in constructor. Manually set it to 1 here
=> Fix flaky EXP calculation tests

src/commands/game_commands/leaderboard.ts
* Extract leaderboard level string out of case statement
* Corrected undefined songs guessed on temporary lb
* Moved up songs guessed example command in lb help
* Pluralize levels gained, songs guessed, games played
=> Fixed bug showing undefined songs guessed; miscellaneous formatting fixes

src/structures/game_session.ts
`endRound` sends the scoreboard message and passes this `messageContext`. It needs the `guildID` for localization
=> Localize no correct guess message on MC

src/structures/guild_preference.ts
If a beginning and end cutoff are set, then cutoff is underlined twice. Solved by removing duplicate options on `resetToDefault()`.
=> Prevent ,cutoff from double underline on ,reset

sql/analytics/guild-preference-by-guild.sql, sql/analytics/recently-active-guilds.sql, sql/analytics/server-joins-by-day.sql, src/fact_generator.ts, src/helpers/game_utils.ts, src/migrations/20220218012204_guild_preferences_to_guild_metadata.js, src/structures/game_session.ts
* This table no longer stores the preferences, only info about guilds such as last activity date, games played, etc.
=> Rename guild_preferences table to guilds

i18n/en.json, i18n/ko.json, src/commands/game_commands/begin.ts, src/commands/game_commands/join.ts, src/commands/game_commands/leaderboard.ts, src/commands/game_commands/play.ts, src/commands/game_options/goal.ts, src/events/client/voiceChannelJoin.ts, src/events/client/voiceChannelSwitch.ts, src/helpers/discord_utils.ts, src/kmq_worker.ts, src/structures/elimination_player.ts, src/structures/elimination_scoreboard.ts, src/structures/game_session.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/team.ts, src/structures/team_scoreboard.ts, src/test/ci/begin.test.ts, src/test/ci/elimination_scoreboard.test.ts, src/test/ci/exp.test.ts, src/test/ci/game_utils.test.ts, src/test/ci/leaderboard.test.ts, src/test/ci/player.test.ts, src/test/ci/scoreboard.test.ts, src/test/ci/team.test.ts, src/test/ci/team_scoreboard.test.ts, src/test/test_setup.ts
* Create Player upon VC entry instead of on-demand or elimination game start
* Remove redundant `participants` in GameSession and use scoreboard to manage instead
* Start elimination game with current VC members instead, and don't require to ,join
* Remove `Scoreboard::isEmpty()` and replace previous checks using it with checking to see if `Scoreboard::firstPlace` is empty (they were relying on the side effect that there are no scoreboard entries when there is no one in first place)
* Show players with 0 points on scoreboard, but only if they are in VC
* Provide more accurate counts of active players for stats by checking players are currently in VC
* Add `EliminationPlayer::fromUserID()`
* Remove redundant `Player::getID()`/`getName()` (already `public readonly`)
=> Refactor of participants, ,play elimination

.gitignore, src/seed/bootstrap.ts, src/seed/seed_db.ts
Adds a frozen schema file in `data/`. Every time we seed the database, we check the new database's schema against the frozen one. If there is a change, the seed will fail. After manually checking the schema update is valid, we can delete the frozen schema file so that a new one can be generated.
=> Add check for changes in Daisuki database schema

src/helpers/localization_manager.ts
`fact.fun.birthday` and `fact.fun.fanclubName` were attempting to be localized on bot startup, but the i18next backend wasn't ready, so they weren't translated
=> Load i18next backend synchronously to fix fact translations

i18n/en.json, i18n/ko.json, src/commands/game_commands/forceskip.ts, src/commands/game_commands/skip.ts, src/events/client/interactionCreate.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/structures/music_round.ts, src/structures/music_session.ts, src/structures/round.ts, src/structures/session.ts
Two interactable buttons that appear only in the music session. Shows ephemeral messages as a response to both. When the majority skip count is achieved, the skip button is disabled and turned green and the round is skipped. The bookmark button never gets disabled
=> Add skip and bookmark buttons in music session

.eslintrc.json, src/commands/game_commands/begin.ts, src/commands/game_commands/forceskip.ts, src/commands/game_commands/music.ts, src/commands/game_commands/play.ts, src/commands/game_commands/skip.ts, src/commands/game_options/timer.ts, src/structures/game_session.ts, src/structures/guild_preference.ts, src/structures/music_session.ts, src/structures/session.ts, src/test/ci/begin.test.ts, src/test/ci/game_session.test.ts, src/test/ci/game_utils.test.ts, src/test/ci/leaderboard.test.ts
- GuildPreferences are now cached
- refactor Session classes to store GuildPreference rather than fetch every time
- enable cyclic dependency ESLint rule
Closes #1280 
Reduces warnings from 2 to 0
=> Cyclic dependency cleanup: Refactor Session to use cached GuildPreference reference

i18n/en.json, i18n/ko.json, src/commands/game_commands/lookup.ts, src/helpers/utils.ts
If user provides a valid URL, we assume that they are providing a youtube link and look up by youtube video ID
Otherwise, we assume they're providing a song name, and we search using song name against `available_songs.` If there are multiple results, we list the matched songs, including pagination if needed. Matches are sorted by song name length, then by views.
If there is only one result, we return a response similar to searching by video ID
=> Add song name search functionality to lookup

src/structures/game_session.ts, src/structures/listening_session.ts, src/structures/session.ts
2022-05-07T17:19:01.672Z [ERROR] - messageCreate | Error while invoking command (play) | 16d436b0-cb84-42a2-93d0-b58d38f2a45c | Exception Name: TypeError. Reason: Cannot read properties of null (reading 'song'). Trace: TypeError: Cannot read properties of null (reading 'song')
at GameSession.<anonymous> (/home/kmq/prod/build/structures/game_session.js:116:47)
at Generator.next (<anonymous>)
at fulfilled (/home/kmq/prod/build/structures/game_session.js:28:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)}
=> Abort game/listening session setup if base startRound fails

src/helpers/discord_utils.ts
Adding reactions requires `readAllMessages` permission
=> Add readAllMessages permission check to help command

src/structures/game_session.ts, src/structures/listening_session.ts
2022-05-11T01:16:11.225Z [ERROR] - unhandledRejection | Cluster Unhandled Rejection at: Reason: TypeError: Cannot read properties of null (reading 'interactionIncorrectAnswerUUIDs'). Trace: TypeError: Cannot read properties of null (reading 'interactionIncorrectAnswerUUIDs')
at GameSession.<anonymous> (/home/kmq/prod/build/structures/game_session.js:125:32)
at Generator.next (<anonymous>)
at fulfilled (/home/kmq/prod/build/structures/game_session.js:28:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
=> Add round nullcheck in handleComponentInteraction

src/commands/game_commands/lookup.ts, src/helpers/game_utils.ts
Was using `whereRaw` because `whereLike` is broken (https://github.com/knex/knex/issues/5143). `whereILike` should work for our usecase too
=> Use whereILike instead of whereRaw

src/constants.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts
Closes #1338.
* Use 23 as the badge ID for Premium Supporter (table definition changed since premium was created) -- "🎧 Premium Supporter" = 23 on prod already
* Fix bug where empty query error thrown in addPremium when no premium users
* Correctly await removePremium db calls
* Update premium status every minute instead of every 5 minutes
=> Fix premium awarding code bugs

.github/reviewers.yml, .github/workflows/auto_request_review.yml
synchronize: Triggered when a pull request's head branch is updated. For example, when the head branch is updated from the base branch, when new commits are pushed to the head branch, or when the base branch is changed.
=> Update reviewers upon branch push

package.json, src/structures/guild_preference.ts, yarn.lock
Causing stale guild preference reference in game session when `,play` and game option update calls `getGuildPreference()` at the same time. If the database query to retrieve the game options finishes in the wrong order, it causes the game session to hold onto a stale guild preference, while `GuildPreference.getGuildPreference()` returns the new one. Game option updates happen on the new game options, not the GameSession's reference. 
Issue resolves itself if the user restarts the session.
=> Fix guild preference creation race condition

src/structures/game_session.ts
Base class' `endRound` sets `this.round = null`, which is checked as a pre-condition in `gameSession.guessSong()`. Moved it to beginning of derived class' `endRound`
=> Fix race condition between end round and song guess

.gitignore, package.json, sql_dumps/kmq-test-cached.sql, src/constants.ts, src/scripts/regenerate-test-db-dump.ts, src/test/test_setup.ts
Applying migrations is ridiculously slow for some reason, and it's much faster to import a SQL dump. Added a cached kmq_test database export(schema is available, no data), which is consumed during tests. This reduces the kmq_test database creation time from ~7.5s to ~1.2s. 
Ideally this file is re-generated every time the schema is updated, but this isn't necessary.
=> Cache kmq_test database schema as sql dump

start.sh
This would give us a stack trace for 
```
Timeout duration was set to 1.
(node:2494510) TimeoutOverflowWarning: 18446744073425852000 does not fit into a 32-bit signed integer.
```
=> Add --trace-warnings flag

src/constants.ts, src/environment.d.ts, src/events/client/warn.ts, src/kmq.ts
Discord's recommended 1000 guilds per shard is too aggressive and spawns an unnecessary number of ws connections, as well as increasing startup time. Recommended upper limit is 2500 guilds per shard, so set 2000 as default with 500 per shard as padding. 
At current 50000 guilds, this would create 25 shards. This means that it would take an increase of 500/(1/25) = 12500 in server growth before needing to re-shard. This would take over 3 months assuming aggressive growth of 120 servers per day.
=> Configure guildsPerShard

.github/workflows/gci-tests.yml
3.6 is no longer supported.
Run actions/setup-python@v2
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
=> Update Python version in GCI

src/commands/game_commands/help.ts
Increased commands shown on per-embed to 8 due to more space
The newlines for each command make the output too long, and with slash commands the usage is self-explanatory. With /help [action], the usage still shows
Also,
* Added / to the start of each command name in /help
* Removed /premium from excluded commands
=> Remove usage from full /help

src/events/client/voiceChannelLeave.ts
When bot is disconnected from it's websocket connection, it emits a voiceChannelLeave event. This goes into the `checkBotIsAlone()` call which checks for a valid voice connection. Since there is no voice connection, it considers the bot alone, and ends the session.
=> Ignore voiceChannelLeave event for bot user

src/command_prechecks.ts, src/commands/game_commands/play.ts, src/commands/game_commands/preset.ts, src/helpers/discord_utils.ts, src/structures/game_session.ts, src/structures/session.ts, src/structures/song_selector.ts, src/test/ci/begin.test.ts
`,play` and `,preset` were the only user-facing commands still showing commas
=> Replace comma with slash in docs/comments

package.json, src/structures/game_session.ts, src/structures/session.ts, yarn.lock
Unsure why but canary transpile was failing due to 
```
1|kmq-2  | Compiling typescript...
1|kmq-2  | src/structures/game_session.ts(226,17): error TS2322: Type 'string | null' is not assignable to type 'string'.
1|kmq-2  |   Type 'null' is not assignable to type 'string'.
1|kmq-2  | src/structures/session.ts(926,17): error TS2322: Type 'string | null' is not assignable to type 'string'.
1|kmq-2  |   Type 'null' is not assignable to type 'string'.
```
Despite the typings for uuid.v4() not including `| null`. Still not sure where it comes from
=> Cast uuids to string

src/commands/game_commands/lookup.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/helpers/spotify_manager.ts, src/structures/game_round.ts, src/test/ci/game_round.test.ts
- Better matching for song names with brackets. e.g "Egoist (Olivia Hye)". Attempts to match each component separately, as well as all together
- Match artists in all lowercase AND punctuation removed
- Match song names with all non-alphanumeric characters removed
- Match against id_parent_artist
=> Improve spotify song matching

src/helpers/game_utils.ts, src/helpers/patreon_manager.ts, start.sh
Previous:
```
knex:query select `user_id` from `premium_users` where `user_id` not in (?, ?, ?) and not `source` = ? undefined +60s
knex:tx trx44: Starting top level transaction +60s
knex:query BEGIN; trx44 +1ms
knex:query update `premium_users` set `active` = ? where `user_id` in (?, ?, ?) trx44 +0ms
knex:query delete from `badges_players` where `user_id` in (?, ?, ?) and `badge_id` = ? trx44 +0ms
knex:query COMMIT; trx44 +0ms
knex:tx trx44: releasing connection +16ms
knex:tx trx45: Starting top level transaction +0ms
knex:query BEGIN; trx45 +15ms
knex:query insert into `premium_users` (`active`, `first_subscribed`, `user_id`) values (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?) on duplicate key update `active` = values(`active`), `first_subscribed` = values(`first_subscribed`), …
```
=> Consolidate add/remove premium into one tx

src/commands/game_options/spotify.ts, src/database_context.ts, src/helpers/spotify_manager.ts
Parallelizing database queries in chunks. Experimented with varying chunk sizes for playlist size of 4214
1 chunk (base case) = 100s - 106s
2 chunk = 61s - 64s
3 chunk = 59s - 61s
4 chunk = 57s - 58s
Diminishing returns after 4 chunk
=> Parallelize spotify matching database lookup

package.json, src/helpers/spotify_manager.ts, yarn.lock
Chunking promises and using Promise.all() causes unnecessary delay when one of the promises takes longer than the others. Switched to using async-pool to maximize concurrency.
Average ~20% decrease in total query time.
For playlist of 4214 songs, 66s -> 55s
For playlist of 2283 songs, 18.5s -> 15.5s
=> Use async promise pool instead of Promise.all for spotify db queries

sql/procedures/create_kmq_data_tables_procedure.sql, src/helpers/spotify_manager.ts
For 4214 song playlist:
Per-query time: 55.65ms -> 29.1ms (-62%)
Total matching time: 58764ms -> 30792ms (-62%)
For 2281 song playlist:
Per-query time: 31ms -> 20.9ms (-38%)
Total matching time: 17841ms -> 12067ms (-38%)
=> Preprocess alphanumeric-only song names for song match

package.json, sql/procedures/create_kmq_data_tables_procedure.sql, src/helpers/spotify_manager.ts, start.sh
Currently, artists with duplicate names get their full name appended in `kpop_groups`. I.e: `YENA (Choi Yena), Yena (Yang Yena), Yena (Jeong Yena)`
Change Spotify matching query to match on the original name, i.e: `Yena`
=> Spotify song match on original artist name (non de-duplicated)

sql/procedures/create_kmq_data_tables_procedure.sql
`clean_song_name_alpha_numeric` was reading from `name`, which often contains additional text in brackets, e.g: `DND (Do Not Disturb)`, which resulted in `DNDDoNotDisturb` which removing non-alpha numeric characters. Remove the brackets beforehand.
=> clean_song_name_alpha_numeric should come from clean_song_name_en

sql/procedures/create_kmq_data_tables_procedure.sql, sql/procedures/deduplicate_app_kpop_group_names.sql, src/seed/bootstrap.ts, src/seed/seed_db.ts, src/test/test_setup.ts
Previously the deduplication was being run every time `CreateKmqDataTables()` was being called, which was on every startup. The deduplication begins by saving the current group name as `original_name`, hence it should only run once.
=> Only deduplicate group names upon database seed

package.json, src/constants.ts, src/helpers/utils.ts, src/kmq.ts, src/seed/seed_db.ts
Will replace with system cronjob running `npm run seed`. Allows changing to the database seed cadence without restarting the KMQ instance. Also allows for updated seed code without restart.
=> Remove internal cronjob for database seed

.github/workflows/gci-e2e.yml
`${{ steps.meta.outputs.tags }}` returns two values `[ghcr.io/brainicism/kmq_discord:nightly, ghcr.io/brainicism/kmq_discord:master]` and confuses the second value as a command to invoke.
=> Hardcode docker image name in e2e gci

src/structures/guild_preference.ts, src/test/ci/guild_preference.test.ts
In commits prior to 66936080f, the value passed into `validateGameOptions` was used to set `this.gameOptions`. After removing this argument, we did not initialize `this.gameOptions` with the loaded preset. Directly setting it before running the validation restores old behavior
=> Fix bug preventing preset from loading

.gitignore, src/helpers/spotify_manager.ts
Prefer non-alternate language matches
Secondary order on number of views
=> Add tiebreaker on Spotify matchers if multiple results

docker/kmq/Dockerfile
Weird bug with the static ffmpeg binary we were using causes streams to play from the beginning regardless of the seek parameters passed. ffmpeg available in the alpine package manager isn't compiled with the flags required for `/special`. Only solution is to either manually compile ffmpeg with the appropriate flags, or revert to Ubuntu image and use the known working version.
=> Revert Docker image to Ubuntu

src/database_context.ts, src/helpers/game_utils.ts, src/kysely/plugins/empty-where-in-plugin/plugin.ts, src/kysely/plugins/empty-where-in-plugin/transformer.ts, src/scripts/download-new-songs.ts, src/structures/song_selector.ts
When we used Knex, `.whereIn("column", [])` would compile into a falsey statement like `WHERE 1 = 2` because `WHERE IN ()` is not valid SQL syntax. 
Kysely will generate the invalid syntax, hence my previous attempts to add array length checks to all WHERE IN queries. This plugin should revert it back to Knex's behavior.
=> Create EmptyWhereIn Kysely plugin

src/structures/game_round.ts, src/test/ci/game_round.test.ts
Keep track of all guesses. For hidden games, use the most recent guess. For non-hidden games, use the oldest correct guess.
=> Fix bug where guess time would get overwritten

src/commands/game_options/spotify.ts, src/constants.ts, src/enums/game_option_name.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/helpers/spotify_manager.ts, src/interfaces/game_options.ts, src/interfaces/matched_playlist.ts, src/interfaces/playlist_metadata.ts, src/scripts/spotify-playlist-metadata-to-id.ts, src/state.ts, src/structures/guild_preference.ts, src/structures/session.ts, src/structures/song_selector.ts, src/test/ci/command_prechecks.test.ts, src/types.ts
* Store only playlistID in game options and game option presets (script needs to be run)
* Cache queried songs and metadata (flushed daily, invalidated on snapshotID change)
* Show spotify thumbnail in /options
* Move MatchedPlaylist, PlaylistMetadata into interface files
=> Prevent stale /spotify metadata

src/commands/game_options/gender.ts
* We only accept a maximum of three gender options (male, female, coed)
* Alternating is not used in conjunction with the above three options
=> Remove extra gender option key

src/commands/game_options/reset.ts
`generateOptionsMessage` received `{"option":"Cutoff","reset":true} {"option":"Cutoff","reset":true}` as the list of `updatedOptions` when `/reset` was called in the case where both the start and end cutoff are reset
=> Fix bug where /reset caused cutoff to be underlined twice

src/helpers/discord_utils.ts
* When a playlist is uncached, it has to be parsed before it's shown in /options
* For non-interaction ,options calls, this leads to users waiting multiple seconds while the playlist is parsed before /options is sent, which makes the bot look unresponsive 
* Added a parsing message, followed by ,options
* For interactions, if it is a large playlist, the bot fails to acknowledge the interaction, and only subsequent calls of /options go through after the playlist is parsed
* Acknowledged the interaction with a parsing message, and used a followup message for /options
=> Fix bug where parsing playlist prevented /options ack

src/commands/game_commands/exp.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/test/ci/game_round.test.ts
In 8bc9ec533671bfbbc5cc5a7b892a28d57923bd33, the switch from storing timestamps to guess times (in seconds) led to an inconsistency when comparing with the quick guess bonus cutoff constant (in milliseconds).
=> Fix bug where quick guess bonus was always applied

docker/kmq/Dockerfile
Docker build fails in newer versions of the node:18 image. required `node-gyp` binary was removed from npm bundle
https://github.com/npm/cli/pull/6554#issuecomment-1726429283
=> Install node-gyp in Dockerfile

sql/procedures/create_kmq_data_tables_procedure.sql
Previously we cleaned song names by splitting on '(' and taking the first component. This breaks when we have song names with genuine brackets in them. Changed the condition such that the cleaning only occurs if the bracket is the last character in the string. 
Closes #1766
=> Fix bug where songs with brackets in middle of name parsed incorrectly

sql/procedures/create_kmq_data_tables_procedure.sql, sql/procedures/post_seed_data_cleaning_procedure.sql, src/seed/seed_db.ts, src/test/test_setup.ts
Original fix did not fix other related columns (`clean_song_name_alpha_numeric, clean_song_name_ko`). Instead, perform the cleaning on the source (`kpop_videos`) directly.
=> Fix bug where songs with brackets in middle of name parsed incorrectly (v2)

src/helpers/reddit_client.ts
Example response pre-change: `We've got teasers, an MV, and even an album discussion to keep us entertained. Stay tuned for more ITZY goodness!`
=> Rename album discussion flair to album

docker/kmq/Dockerfile
Keep health as every 5 seconds during start-up, but once per minute once container is healthy.
=> Longer docker health check after start period

src/helpers/discord_utils.ts
```
2024-03-01T13:28:06.404Z [ERROR] - interactionCreate | gid: 679165980995223582, tid: 965132486290071563 | Error while invoking command (CHAT_INPUT CommandInteraction interaction for 'lookup') | e442a45f-bb87-4496-ae0a-c081e3cb90d9 | Exception Name: DiscordRESTError [50001]. Reason: Missing Access. Trace: DiscordRESTError [50001]: Missing Access
```
This happens at `eris-pagination/lib/PaginationEmbed.js:104`, when trying to add the pagination reaction emojis to the interaction message.
```ts
await this.message.addReaction(this.back);
await this.message.addReaction(this.forth);
```
When the bot doesn't have `viewChannel` permissions, it cannot add a reaction. But chat input interactions can still be used from that channel. Added `viewChannel` as a required permission.
=> Add viewChannel as required text permission

src/constants.ts, src/helpers/discord_utils.ts, src/kmq_worker.ts
https://discord.com/developers/docs/interactions/application-commands#updating-and-deleting-a-command
Application commands do not change their IDs, and command updates to the same type/scope are treated as upserts. 
Cache and load from cache upon startup incase of command update timing out.
=> Cache app command IDs

src/commands/admin/appcommands.ts, src/events/client/messageCreate.ts, src/helpers/discord_utils.ts, src/kmq.ts, src/kmq_worker.ts
- `,appcommand reload` now reloads all clusters
- More logging for `bulkEditCommands` 
- Automatically fetch from cached on bulkEditCommand failure
=> Application command update improvements

src/commands/game_commands/lookup.ts, src/commands/game_options/playlist.ts, src/helpers/game_utils.ts, src/structures/game_session.ts, src/structures/guild_preference.ts, src/structures/listening_session.ts, src/structures/session.ts, src/structures/song_selector.ts, src/test/ci/game_session.test.ts, src/test/ci/listening_session.test.ts, src/test/ci/song_selector.test.ts
SongSelector is used outside of the context of a Session, since it's the source of truth for anything song count related. Makes more sense to attach it to 1:1 with GuildPreference
=> Refactor SongSelector into GuildPreference

src/commands/game_commands/forceskip.ts, src/commands/game_commands/skip.ts, src/interfaces/guess_result.ts, src/structures/game_session.ts, src/structures/listening_session.ts, src/structures/session.ts, src/test/ci/game_session.test.ts
We were using `GuessResult` for
```
{
correct: true,
correctGuessers: round.correctGuessers,
error?
}
```
We have access to `round.correctGuessers` later in the codepath already, and `correct` is just whether `round.correctGuessers` has a value.
=> Remove GuessResult and use round guessers directly

src/constants.ts
closes #1955
(Reverse) Chronological shuffle types affect the querybuilder
```ts
queryBuilder = queryBuilder
.orderBy(
sql`SUBSTRING(publishedon, 1, ${"YYYY-MM".length})`,
shuffleType === ShuffleType.CHRONOLOGICAL ? "asc" : "desc",
)
.orderBy(sql`RAND()`);
```
=> Mark ShuffleType as reload-impactful game option

src/helpers/playlist_manager.ts
Spotify matching searches for `id_parentgroup`, `id_artist`, and `id_parent_artist` simultaneously incase spotify has labelled it incorrectly. This causes issues when an artist and their parent group both have a song of the same name. 
e.g: 
EXO - diamond
Baekhyun - diamond
Prioritize exact match on artist name before going for other options
=> Spotify match prioritize exact artist match

src/structures/guild_preference.ts, src/test/ci/guild_preference.test.ts
Deadlocks occurring due to gaplocking: http://thushw.blogspot.com/2010/11/mysql-deadlocks-with-concurrent-inserts.html?m=1
Easiest way to avoid is ordering the inserts alphabetically by columns in the constraint, in this case, `option_name`
=> Sequential and alpha-ordered game option inserts

src/commands/game_options/playlist.ts, src/events/client/messageCreate.ts, src/helpers/game_utils.ts, src/structures/guild_preference.ts, src/structures/session.ts, src/structures/song_selector.ts
We were relying on passing in kmqPlaylistID into `reloadSongs`, which most invocations were doing already, except for in `/lookup`. Since `/lookup` wasn't passing a `kmqPlaylistID`, reload went into the non-playlist reload path.
=> reloadSong should read from playlistID from GuildPreference

src/structures/game_round.ts, src/structures/game_session.ts, src/test/unit_tests/ci/game_round.test.ts
Previous PR removed a `.sort()` on guess time prior to getting the first guesser, which was used to calculate streaks.
=> Sort correctGuessers from getter, fix streak bug

src/helpers/discord_utils.ts, src/test/end-to-end-tests/test-runner-bot.ts
Redundant because the test-runner only reads messages that KMQ 'replied' to
=> Handle error for test-runner RUN_ID reply

src/structures/guild_preference.ts
Object property was `option_name` not `optionName`. Switched to type-safe `.sort` instead
=> Fix updatedOptions sorting

src/test/end-to-end-tests/test-runner-bot.ts
This was from before the test runner always tried to react to the latest message sent in the chat. Now it only replies to message replies from KMQ.
=> Don't abort test-runner early on messageCreate

sql/procedures/create_kmq_data_tables_procedure.sql, sql/procedures/generate_expected_available_songs_procedure.sql, src/scripts/download-new-songs.ts, src/seed/seed_db.ts, src/test/unit_tests/test_setup.ts, src/typings/kmq_db.d.ts
Previously both `getSongsFromDb()` (getting songs to download during seed) and `CreateKmqDataTables()` (checking which songs are downloaded to persist to available_songs) replicated the same query. Created intermediate table `expected_available_songs`
=> Generate expected_available_songs as source of truth

sql/procedures/create_kmq_data_tables_procedure.sql, src/commands/game_commands/lookup.ts, src/commands/game_commands/upcomingreleases.ts, src/fact_generator.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/seed/seed_db.ts, src/structures/song_selector.ts, src/typings/kmq_db.d.ts, src/typings/kpop_videos_db.d.ts
`app_kpop_group` gets updated during seed, and modified again during `CreateKmqDataTables` to add the `has_songs` field. This means that in-between the time that we seed the new `app_kpop_group`, until `CreateKmqDataTables()` finishes, the table is missing the `has_songs` field. Which causes errors like:
```
2024-03-23T16:21:26.167Z [ERROR] - interactionCreate | gid: 1006822328610603099, tid: 1221128968573554812 | Error while invoking command (CHAT_INPUT CommandInteraction interaction for 'groups') | cf4adccf-4e15-4689-9306-82e3162ded2c |  Data: {"id":"1213407215453732934","name":"groups","options":[{"name":"add","options":[{"name":"group_1","type":3,"value":"Seventeen"}],"type":1}],"type":1} | Exception Name: Error. Reason: Unknown column 'has_songs' in 'where clause'. Trace: Error: …
```
=> Create app_kpop_groups_safe for safe access during seed

.github/workflows/gci-e2e.yml, src/helpers/discord_utils.ts, src/test/end-to-end-tests/test-runner-bot.ts
We used to use `CURRENT_STAGE.messageId = await sendCommand(command);` to check if KMQ's response matched the test runner's command. However, `await sendCommand(command)` might finish and go directly to `messageCreate` before `messageId` is assigned. 
Instead, use RUN_ID and let KMQ respond with what command it's replying to
=> Use RUN_ID and commandExecuted instead of reference ID

src/helpers/discord_utils.ts
Happens when `/lookup` returns more than one result, but less than two embeds worth of results, which goes into `sendMessage` path. Goes into the test-runner response code path with the interaction ID as the message reference, which isn't a valid message.
=> Fix lookup interaction bug

src/structures/game_session.ts
```
2024-03-27T18:33:26.461Z [ERROR] - unhandledRejection | Cluster Unhandled Rejection | Name: TypeError. Reason: Cannot read properties of null (reading 'guildID'). Trace: TypeError: Cannot read properties of null (reading 'guildID')
at GameSession.updateGuessedMembersMessage (/app/build/structures/game_session.js:584:118)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Timeout._onTimeout (/app/build/structures/game_session.js:1010:13)}
```
Assuming this is some race condition where `round.interactionMessage` gets set to null elsewhere
=> Use this.guildID in updateGuessedMembersMessage

src/environment.d.ts, src/kmq_web_server.ts, src/kmq_worker.ts, src/test/end-to-end-tests/test-runner-bot.ts, start.sh
Generate RUN_ID from KMQ side to prevent issue where multiple KMQ instances re-using same RUN_ID
=> Assign RUN_ID on KMQ startup

src/structures/game_round.ts, src/structures/queried_song.ts, src/test/unit_tests/ci/game_round.test.ts
Users have been abusing this mechanic by switching to Korean locale for a newly generated hint
=> Hints should be same if Korean name is same

src/commands/game_options/playlist.ts, src/structures/song_selector.ts
Idk how this happened in prod, but this can happen with:
1. `/playlist` with Spotify playlist with 1 song that matches
2. Remove song from playlist
3. Do something to trigger `reloadSongs` with metadata refresh, which will load 0 songs while playlist data is still persisted
4. `/spotify matches`
```
2024-04-02T15:04:43.232Z [ERROR] - interactionCreate | gid: 343260119934697483, tid: 1203535494181421118 | Error while invoking command (CHAT_INPUT CommandInteraction interaction for 'spotify') | 4f1baa48-2dd9-4791-a8e4-d47df7faaa03 |  Data: {"id":"1212643928730509381","name":"spotify","options":[{"name":"matches","options":[],"type":1}],"type":1} | Exception Name: DiscordRESTError [50006]. Reason: Cannot send an empty message. Trace: DiscordRESTError [50006]: Cannot send an empty message
at …
```
=> Playlist with zero matches/unmatched error handling

src/scripts/announce-restart.ts
* By default, the parent will wait for the detached child to exit. To prevent the
* parent from waiting for a given `subprocess` to exit, use the`subprocess.unref()` method. Doing so will cause the parent's event loop to not
* include the child in its reference count, allowing the parent to exit
* independently of the child, unless there is an established IPC channel between
* the child and the parent.
=> Unref post-upgrade test runner execution

src/helpers/discord_utils.ts
2024-04-05T19:10:16.198Z [ERROR] - discord_utils | Error sending message. Unknown generic error. textChannelID = 1196846707883913317. Name: Error. Reason: connect ETIMEDOUT 162.159.136.232:443. Stack: Error: connect ETIMEDOUT
=> Update sendMessageExceptionHandler timeout strings

src/helpers/discord_utils.ts, src/kmq_worker.ts
channel.getMessage() performs a REST call to fetch message from API.
=> Fetch test-runner messages from cache

src/structures/game_session.ts, src/test/end-to-end-tests/test-runner-bot.ts, src/test/end-to-end-tests/test_suites/gameplay_test.ts, src/test/end-to-end-tests/test_suites/test_suite.ts
`this.round` points to the new round after one correct guess has been submitted. If two correct guesses are submitted simultaneously, the second invocation has a reference to the new game round, so it accidentally skips it. 
Closes #2079
=> Fix race condition for double startRound() during correct guess

src/structures/session.ts
Only occurs when song_start_delay is 0
=> Fix bug where clip mode last replay caused duplicate endRound

src/helpers/discord_utils.ts
`State.client.guilds` only contains guild cache for the guilds on that the specific shards that the curerent cluster is holding. The `if (!debugGuild) return` would fail if running `,debug` on any cluster other than the one holding the debug server. 
`fetchChannel` already searches for the channel in other clusters via ipc
=> Fix getDebugChannel for multicluster deployments

src/structures/session.ts
`.once()` already removes the listener after the first event is triggered. Removing all listeners was also removing the listener set in `ensureVoiceConnection()` to log warnings during abnormal WS errors, causing uncaught exceptions.
=> Remove redundant error listener removal

src/structures/session.ts
Forgot that we had a `this.connection.once("error")` and we were no longer removing `error` events in #2120, causing a leak. Instead, revert to removing all listeners but re-attaching the generic error one that we need
```
2024-04-27T22:27:47.430Z [ERROR] - Cluster 0 | (node:52) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [VoiceConnection]. Use emitter.setMaxListeners() to increase limit
at _addListener (node:events:591:17)
at VoiceConnection.addListener (node:events:609:10)
at VoiceConnection.once (node:events:653:8)
at GameSession.playSong (/app/build/structures/session.js:545:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async GameSession.startRound (/app/build/structures/session.js:167:40) …
```
=> Remove and renew connection listeners on ensureVoiceConnection

src/helpers/discord_utils.ts
Channels fetched via IPC do not include `.guild` data
=> Only cache text channel if contains guild data

src/commands/game_commands/profile.ts, src/helpers/discord_utils.ts
Objects fetched over IPC are missing certain properties (`channel.guild`) and methods (`channel.permissionOf`). Better to just grab via REST and update cache.
=> Remove fetching structures via IPC

src/scripts/announce-restart.sh
`docker run` will automatically pull the image if it doesn't exist locally. But in our E2E workflow, we are trying to re-use the image that already exists locally. Doing a `docker pull` will download the older images on GH registry that we no longer use.
=> Remove unnecessarily docker pull in announce-restart

.github/workflows/gci-e2e.yml, docker/kmq/Dockerfile, src/kmq_configuration.ts, src/scripts/download-new-songs.ts, src/scripts/session-generator.sh
Using cookie is recommended over passing visitor data to extractor because passing visitor data means `It requires skipping webpage requests so the VISITOR_INFO1_LIVE cookie does not interfere, which will mean more requests, and less stable extraction.`  and `yes, as you are technically using fallbacks. so e.g if that iframe request gets 429nd, the nsig/sig transforming will fail`
https://github.com/yt-dlp/yt-dlp-wiki/blob/761b7d71bdad5f7a91326beb4757471d41b4821b/Extractors.md
=> Support visitor id cookie

sql/procedures/generate_expected_available_songs_procedure.sql
Accounts for a very small minority of songs (~20), mostly in Korean. Likely auto-added by Daisuki and haven't had their entries updated with english names yet. 
Considered hiding them based on locale but was too much work to support that. These songs have historically low popularity anyway, and would only affect korean locale players.
=> Ignore songs without english names

sql/procedures/generate_expected_available_songs_procedure.sql
We are removing bracketed parts of song names for entries like `Song (X Version) => Song`. But there are some songs where the bracket occurs in the middle of the name, like `Ab(c) De => Ab`  
Example song names:
```
NY(f)C
FRI(END)S
Dream (s) 1
Dream (s) 2
Dream (s) 3
```
Modify to check that bracket ends at the end of the string before removing them
=> Don't remove bracketed component if in middle of song name

package.json
`/sql_dumps/daisuki` wasn't being mounted, so we aren't keeping old dumps after container is re-created.
=> Add daisuki dumps to container mount

src/helpers/kmq_song_downloader.ts
Previously always began with first proxy in the list, which would have frontloaded the first proxy if few songs are downloaded each time
=> Randomize first proxy selection

src/structures/game_round.ts, src/test/unit_tests/ci/game_round.test.ts
`song.artistName.split("+")` was returning an empty string for `24K+` and `Mamamoo+`. Check for collabs using `% + %` instead.
=> Fix accepted artist name answers for artist with + in name

src/helpers/kmq_song_downloader.ts
[libopus @ 0x5574da8208c0] Invalid channel layout 5.1(side) for specified mapping family -1.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
fEqkhH1pUbA
Discord only supports stereo
=> Force stereo audio

.devcontainer/post_create_command.sh, .github/workflows/gci-e2e.yml, .github/workflows/gci-tests.yml, docker/kmq/Dockerfile, package-lock.json, package.json, src/helpers/kmq_song_downloader.ts, src/kmq_configuration.ts, src/scripts/generate-yt-session-bgutils.ts, src/youtube_onesie_provider.ts, start.sh, yarn.lock
Temporary switch to npm since googlevideos package doesn't support yarn right now.
=> Support onesie requests

src/structures/session.ts
Voice connection automatically calls `stopPlaying` and emits `'end'` when `voiceDataTimeout` time passes before any audio is played. For some `/special` modes, time to first audio output is longer than the default of 2000ms.
=> Increase voiceDataTimeout for /special mode

src/helpers/gemini_client.ts
Gemini 1.0 pro is deprecated on February 15. For 1.0's free tier, 15 RPM, 32,000 TPM, and 1,500 RPD are supported. For 1.5's free tier, 15 RPM, 1 million TPM, and 1,500 RPD are supported, so additional rate limiting is not expected.
https://ai.google.dev/gemini-api/docs/models/gemini#gemini-1.0-pro
=> Upgrade to gemini-1.5-flash
