Brainicism/KMQ_Discord

kmq.js
=> Added space

help_strings.json, kmq.js
Help text comes from help_strings.json and are sent as a command
=> Add Helper Text

commands/cutoff.js, commands/end.js, commands/gender.js, commands/help.js, commands/random.js, commands/stop.js, helpers/validate.js, kmq.js, models/game_session.js
=> Parameter validation [#29]

commands/skip.js, helpers/guess_song.js, kmq.js
=> Enabled continuous playback, bot doesn't leave VC in between songs [#45]

commands/help.js
Command will be shown in `code` format
=> Display command usage in per-command help message [#62]

kmq.js
Can't send the song message because there is no way for us to get the text channel
=> End round when all users leave VC [#76]

helpers/utils.js, package.json
Added hangul-romanization module
=> Romanized hangul song titles for guesses [#72]

commands/cutoff.js, commands/end.js, commands/gender.js, commands/limit.js, commands/prefix.js, commands/random.js, commands/skip.js, commands/stop.js, helpers/guess_song.js, helpers/utils.js, kmq.js, models/game_session.js, models/guild_preference.js
Deferred GameSession creation to game start [#85]
=> Persist server settings in DB, added separate class for per-guild preferences [#78]

commands/skip.js, helpers/utils.js
Also send the song message when current one ends or fails to play.
Skip wasn't supposed to show message author picture and name, so I removed it.
=> Start new song when current song ends, increase playback bitrate [#81]

commands/prefix.js, commands/volume.js, data/help_strings.json, helpers/utils.js, models/game_session.js, models/guild_preference.js
- Added missing help string for prefix
=> Implemented volume control [#87]

README.md, commands/random.js, commands/skip.js, helpers/utils.js, kmq.js, models/game_session.js, package-lock.json, package.json
Doesn't fix song cutting off early, even with `highWaterMark` parameter. Code changes are necessary for Discord.js v12.
=> Updated Discord.js to v12, updated other dependencies

helpers/utils.js
- Increased song chunk loading size
- I'm dumb
=> Correctly restart song at end of song

helpers/utils.js, kmq.js, models/guild_preference.js
=> Made MySQL connection agnostic of database

models/game_session.js
For code readability and clarity (and to fix bug with logging)
=> Renamed GameSession's _link to _videoID

package-lock.json, package.json
https://github.com/fent/node-ytdl-core/issues/614
=> Updated ytdl-core to 2.1.2 to fix playback error

config.json.template, kmq.js, package-lock.json, package.json
=> Added functionality to post server count to top.gg [#130]

helpers/utils.js
=> Warn user of missing VC permissions, end GameSession

README.md, commands/play.js, data/help_strings.json, kmq.js
=> Add command aliasing, add alias for ,play

src/helpers/discord_utils.ts, src/helpers/game_utils.ts
Also added logger error if cache directory doesn't exist/is not found
=> Ignore messages if the user is not playing in VC

src/helpers/discord_utils.ts, src/scripts/download-new-songs.ts, src/seed/seed_db.ts
=> Replace fs callbacks with promises

package-lock.json, package.json, src/helpers/game_utils.ts
=> Seek to random part of song rather than the beginning [#164]

src/commands/help.ts, src/commands/news.ts, src/commands/ransom.ts, src/commands/skip.ts, src/helpers/discord_utils.ts
=> Check for text channel SEND_MESSAGES permission [#143]

src/commands/news.ts
=> Show date of latest song in ,news [#84]

src/commands/skip.ts, src/commands/stop.ts, src/helpers/game_utils.ts, src/kmq.ts, src/models/game_session.ts
=> Destroy stream dispatchers when song is done

src/commands/cutoff.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/models/guild_preference.ts
=> Add game option for upper cutoff year [#178]

config/app_config.json.template, data/group_list.txt, package-lock.json, package.json, src/config_validator.ts, src/helpers/bot_stats_poster.ts, src/kmq.ts
Refactored top.gg to use same periodic updating. Can't test unless on prod
Closes [#192 ]
=> Add bot stats posting to discord.bots.gg

config/app_config.json.template, migrations/20200726213404_restart_table.js, package-lock.json, package.json, src/commands/play.ts, src/config_validator.ts, src/helpers/game_utils.ts, src/kmq.ts, src/models/game_session.ts, src/scripts/announce-restart.ts
=> Notifications for upcoming bot restarts

src/helpers/game_utils.ts
=> Ignore apostrophe in song guesses [#208]

src/commands/play.ts
=> Only display game session start message upon first start [#212]

migrations/20200802155423_usage-data.js, src/commands/end.ts, src/commands/skip.ts, src/commands/stop.ts, src/helpers/game_utils.ts, src/kmq.ts, src/models/game_session.ts
=> Add server usage data collection

src/commands/skip.ts
=> Don't delete skip message (hence instantly starting new song) [#188]

README.md, src/commands/mode.ts, src/commands/seek.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/models/game_round.ts, src/models/game_session.ts, src/models/guild_preference.ts
=> Add game option to change guessing mode (artist vs song)

src/helpers/validate.ts, src/models/guild_preference.ts
=> Automatically apply lowercase to enum validated inputs

src/commands/cutoff.ts, src/commands/gender.ts, src/commands/groups.ts, src/commands/limit.ts, src/commands/mode.ts, src/commands/seek.ts, src/commands/volume.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/models/guild_preference.ts
=> Convert constants to enums where needed

src/fact_generator.ts, src/helpers/discord_utils.ts
=> Add occasional random kpop/kmq related fun facts to embed messages

src/helpers/discord_utils.ts
Why did someone do this
Closes #242
=> Truncate groups string in options message

src/commands/score.ts, src/helpers/discord_utils.ts
=> Add scoreboard command

src/kmq.ts
=> Clean up game sessions on SIGINT

src/kmq.ts
=> Check if bot is alone when participant switches voice channels

src/commands/skip.ts
=> Ignore skip request if game round is finished

GAMEPLAY.md, src/commands/end.ts, src/commands/goal.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/models/game_session.ts, src/models/guild_preference.ts
=> Added goal option [#156]

src/commands/help.ts, src/events/client/connect.ts, src/events/client/error.ts, src/events/client/messageCreate.ts, src/events/client/ready.ts, src/events/client/shardDisconnect.ts, src/events/client/shardReady.ts, src/events/client/shardResume.ts, src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/events/client/warn.ts, src/events/process/SIGINT.ts, src/events/process/uncaughtException.ts, src/events/process/unhandledRejection.ts, src/helpers/discord_utils.ts, src/helpers/management_utils.ts, src/kmq.ts, src/models/game_session.ts, src/types.ts
- Create individual event handler exports for both client and process events
- Refactor kmq.ts
=> Refactor kmq.ts

src/commands/base_command.ts, src/commands/help.ts, src/commands/news.ts, src/commands/skip.ts, src/commands/stats.ts, src/config_validator.ts, src/databases.ts, src/events/client/messageCreate.ts, src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/fact_generator.ts, src/helpers/bot_stats_poster.ts, src/helpers/debug_utils.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/helpers/validate.ts, src/kmq.ts, src/logger.ts, src/models/game_round.ts, src/models/game_session.ts, src/models/guild_preference.ts, src/scripts/announce-restart.ts, src/scripts/download-new-songs.ts, src/scripts/get-unclean-song-names.ts, src/scripts/remove-redunant-aliases.ts, src/seed/seed_db.ts, src/types.ts, tsconfig.json
Allows default imports for modules without default exports.
=> Enable esModuleInterop ts config flag

data/group_list.txt, src/kmq.ts
Fixes issues where newly created voice channels would not be joinable
=> Enable GUILD_ROLE_UPDATE, CHANNEL_CREATE, CHANNEL_DELETE

package-lock.json, package.json, src/helpers/discord_utils.ts, src/kmq.ts, src/models/game_session.ts, src/models/player.ts, src/models/scoreboard.ts
https://github.com/abalabahaha/eris/compare/master...Brainicism:master
=> Use Eris fork with limited cache

src/commands/end.ts, src/commands/gender.ts, src/commands/groups.ts, src/commands/help.ts, src/commands/news.ts, src/commands/options.ts, src/commands/score.ts, src/commands/stats.ts
=> Added logging to command invocations which had no logging

GAMEPLAY.md, src/commands/goal.ts, src/commands/timer.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/models/game_session.ts, src/models/guild_preference.ts
=> Timer command [#291]

GAMEPLAY.md, src/commands/forceskip.ts, src/commands/play.ts, src/models/game_session.ts
Aliases to `,fskip`, `,fs`
Closes #301.
=> Added forceskip feature [#301]

src/commands/groups.ts
=> Groups github URL correction

src/commands/end.ts, src/commands/groups.ts, src/commands/play.ts, src/commands/skip.ts, src/data/group_list.txt
`,p`- play
`,e` - end
`,s` - skip
`,fs` - force-skip (To be added in other branch)
=> Added single-letter aliases

src/environment.d.ts, src/events/client/guildCreate.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts
Not user-facing. We can use this debug channel for other information in the future.
=> Add server join message in a debug channel

src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/models/guild_preference.ts, src/seed/create_available_songs_table.sql, src/seed/seed_db.ts
=> Use materialized view instead of performing JOIN query each time

src/scripts/download-new-songs.ts
ffmpeg logger improvements also
=> Update list of downloaded songs after converted to ogg

src/commands/game_commands/forceskip.ts, src/commands/game_commands/skip.ts, src/helpers/discord_utils.ts, src/models/game_session.ts
=> Fix bug where multiple players could get points for same round

src/helpers/game_utils.ts, src/models/game_session.ts
=> Prevent songs from repeating in succession [#308]

src/models/game_session.ts
=> Call endSession after song query error [#324]

src/commands/game_options/limit.ts
=> Disallow users from setting limit when total song count is 0

src/helpers/utils.ts, src/models/scoreboard.ts
Addresses issues with floating point arithmetic
=> Only display decimal places for strictly decimal values

src/models/game_session.ts
=> Fix bug where ensurePlayerStat called twice for same player

src/commands/game_options/reset.ts, src/models/guild_preference.ts
is this better or worse than using true/false :thinking:
=> updateGuildPreferences call informs whether available songs may change [#376]

src/commands/game_options/cutoff.ts, src/commands/game_options/gender.ts, src/commands/game_options/goal.ts, src/commands/game_options/limit.ts, src/commands/game_options/mode.ts, src/commands/game_options/seek.ts, src/commands/game_options/shuffle.ts, src/models/guild_preference.ts, src/scripts/get-unclean-song-names.ts, src/scripts/remove-redunant-aliases.ts
=> Use default options when game options with no args [#370]

migrations/20201123155842_store-daily-stats.js, src/scripts/store-daily-stats.ts
I'll setup the daily cronjob to call this directly on prod
=> Added script to store daily stats in kmq db

migrations/20201123155842_store-daily-stats.js, package-lock.json, package.json, src/helpers/management_utils.ts, src/scripts/store-daily-stats.ts
Is it safe to `import state` when there isn't a guarantee that the bot is running?
=> Added server count to daily_stats

src/scripts/download-new-songs.ts
=> Renice ffmpeg to 20 (lowest priority) to limit cpu usage [#382]

src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/scripts/announce-restart.ts, src/scripts/download-new-songs.ts, src/seed/seed_db.ts
=> Add cron-scheduled database seed and group update

src/helpers/management_utils.ts, src/kmq.ts, src/models/game_round.ts, src/models/game_session.ts, src/types.ts
=> Add artist/song aliases to global state, error handling

GAMEPLAY.md, src/commands/game_options/exclude.ts, src/commands/game_options/gender.ts, src/commands/game_options/groups.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/models/guild_preference.ts, src/types.ts
=> Add exclude groups game option

src/commands/admin/stats.ts, src/commands/base_command.ts, src/commands/game_commands/end.ts, src/commands/game_commands/forceskip.ts, src/commands/game_commands/help.ts, src/commands/game_commands/news.ts, src/commands/game_commands/options.ts, src/commands/game_commands/play.ts, src/commands/game_commands/score.ts, src/commands/game_commands/skip.ts, src/commands/game_options/cutoff.ts, src/commands/game_options/exclude.ts, src/commands/game_options/gender.ts, src/commands/game_options/goal.ts, src/commands/game_options/groups.ts, src/commands/game_options/limit.ts, src/commands/game_options/mode.ts, src/commands/game_options/reset.ts, src/commands/game_options/seek.ts, src/commands/game_options/shuffle.ts, src/commands/game_options/timer.ts
=> Add priority-based ordering for help command

src/helpers/discord_utils.ts
=> Add details for fixing bot permissions, clarify some text

src/commands/game_commands/forceskip.ts, src/commands/game_commands/skip.ts, src/models/elimination_scoreboard.ts, src/models/game_session.ts, src/models/guild_preference.ts, src/models/scoreboard.ts
Check for gameFinished inside each endRound call
- Replaces the check inside setTimeout
- No longer need the check inside ,forceskip and ,skip
=> End game on skip and forceskip

src/scripts/announce-restart.ts
KMQ logs move too fast to show us anything useful from the restart notifications. Replacing with countdown timer instead
=> Remove kmq log tailing from announce restart script

data/end_game_messages.json, migrations/20210117140712_leaderboard_enrollment.js, src/commands/game_commands/leaderboard.ts
=> Add leaderboard display name enrollment and pagination

migrations/20210117201417_leaderboard_enrollment_display_charset.js
=> Allow utf-8 display names in leaderboard enrollment

docs/GAMEPLAY.md, src/commands/game_options/gender.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/structures/game_session.ts, src/structures/guild_preference.ts
=> Add support for ,gender alternating

data/end_game_messages.json, docs/GAMEPLAY.md, src/commands/game_options/artisttype.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/seed/bootstrap.ts, src/seed/create_available_songs_table_procedure.sql, src/structures/guild_preference.ts, src/types.ts
=> Add game option to specify soloists/groups/both

src/scripts/download-new-songs.ts
=> Encode opus directly after mp3 download, pseudo download throttling

src/commands/game_commands/join.ts, src/structures/elimination_scoreboard.ts, src/structures/game_session.ts
=> Add ability to join elimination game midway

src/scripts/announce-restart.ts
=> Fix bug where announce-restart script didn't terminate

src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/structures/game_session.ts
=> Show songs correctly guessed and total songs in endGame footer [#482]

src/scripts/download-new-songs.ts, src/scripts/volume-fixer.py
=> Normalize encoded song volumes to -30db, add script to remove quiet songs

data/end_game_messages.json, docs/GAMEPLAY.md, src/commands/game_commands/news.ts, src/commands/game_options/language.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/structures/guild_preference.ts, src/types.ts
=> Add language option to filter non-korean songs

src/helpers/game_utils.ts, src/seed/seed_db.ts, src/structures/guild_preference.ts
=> Include artist collabs when specifying artist in ,groups

src/commands/game_commands/leaderboard.ts
=> Leaderboard medal only shows on first page

src/helpers/utils.ts, src/scripts/download-new-songs.ts
Also added quotes around mp3File in ffmpeg to deal with spaces in path
=> Retry song download when mp3.part is missing in download-new-songs

.eslintrc.json, docs/GAMEPLAY.md, src/commands/game_options/subunits.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/seed/create_available_songs_table_procedure.sql, src/structures/guild_preference.ts, src/types.ts
=> Add game option for subunit inclusion preference

src/structures/game_session.ts
=> Increment gamesPlayed on end of round

docs/GAMEPLAY.md, src/structures/game_session.ts
=> Add bonus xp for quick guesses

src/helpers/discord_utils.ts, src/structures/game_session.ts, src/types.ts
=> Add guess streaks

src/fact_generator.ts, src/helpers/utils.ts
=> chooseRandom returns null instead of [], filter empty fun facts

package-lock.json, package.json, src/seed/seed_db.ts
- Fix typo in `forceReseed`
- Only re-seed database once if `-r` and `-p` are both specified
- Remove `sql_mode` and it's dependencies
=> Various seed db fixes

src/structures/game_session.ts
=> Change wording on ensureVoiceConnection exception user-facing message

docs/GAMEPLAY.md, src/commands/game_commands/list.ts, src/structures/guild_preference.ts
=> Add command to list groups options

src/helpers/game_utils.ts, src/structures/game_session.ts, src/structures/guild_preference.ts
Instead reset when there are no unique songs that can be played
=> Persist unique songs queue on options change

src/seed/kpop_videos_overrides.sql
=> Override app_kpop_group.name to use utf8mb4 charset

data/group_list.txt, sql/kpop_videos_overrides.sql
=> Add override to remove comma from 'Car, the garden'

sql/create_kmq_data_tables_procedure.sql, src/helpers/game_utils.ts, src/scripts/download-new-songs.ts, src/scripts/remove-redunant-aliases.ts, src/seed/bootstrap.ts, src/seed/seed_db.ts
=> Copy kpop_groups to kmq database, read from kmq instead

src/commands/game_options/duration.ts, src/helpers/discord_utils.ts
=> Add options for incremental/decremental duration changes

src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/helpers/game_utils.ts
=> Check if gamesession is already finished before ending

src/commands/admin/stats.ts, src/commands/game_commands/debug.ts, src/commands/game_commands/leaderboard.ts, src/commands/game_commands/news.ts, src/commands/game_commands/profile.ts, src/helpers/discord_utils.ts
Also raise probability of KMQ end game messages to 50%
=> Remove already bold titles from sendInfoMessage calls

.eslintrc.json, data/end_game_messages.json, docs/GAMEPLAY.md, src/commands/game_options/multiguess.ts, src/helpers/discord_utils.ts, src/structures/elimination_scoreboard.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/structures/guild_preference.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/team_scoreboard.ts, src/test/ci/elimination_scoreboard.test.ts, src/test/ci/scoreboard.test.ts, src/test/ci/team_scoreboard.test.ts, src/test/test_setup.ts, src/types.ts
=> Multiguess command

src/structures/elimination_scoreboard.ts, src/structures/game_session.ts, src/structures/scoreboard.ts, src/structures/team_scoreboard.ts, src/test/ci/elimination_scoreboard.test.ts, src/test/ci/scoreboard.test.ts, src/test/ci/team_scoreboard.test.ts
Update updateScoreboard to take in multiple inputs
Closes [#638
=> Elimination multiguess no longer removes lives of correct guessers

src/helpers/discord_utils.ts
=> Ensure embed payload author is higher priority than message context

src/helpers/discord_utils.ts
=> Add check for viewChannel VC permission

src/events/client/guildAvailable.ts, src/events/client/unavailableGuildCreate.ts, src/helpers/discord_utils.ts, src/helpers/management_utils.ts
Also send textChannelID and textChannel permissions on sendMessage failure
=> Log guildAvailable, unavailableGuildCreate

src/database_context.ts, src/helpers/management_utils.ts, src/scripts/download-new-songs.ts, src/scripts/remove-redunant-aliases.ts, src/seed/bootstrap.ts, src/seed/seed_db.ts
=> Validate Daisuki SQL dump prior to seed

src/seed/seed_db.ts
=> Automatically prune SQL dumps older than 10 days

.dockerignore, docker/.env.sample, docker/docker-compose.yml, src/scripts/download-new-songs.ts
=> Avoid including .env file in docker image

sql/create_kmq_data_tables_procedure.sql, src/scripts/download-new-songs.ts, src/seed/bootstrap.ts
Reduces bootstrap time from 7 seconds to < 1 second
Reduces setup time of `downloadNewSongs` from 22 seconds to < 1 second
=> Optimize bootstrap/seed processes

src/events/client/messageCreate.ts
=> Split command message by arbirary number of whitespace

src/commands/game_commands/profile.ts, src/helpers/utils.ts
=> Add roman numeral suffix for rank past max rank title

src/structures/game_round.ts, src/structures/game_session.ts, src/structures/kmq_member.ts
=> Fix incorrect points calculation for ,mode both + ,multiguess on

src/commands/game_commands/preset.ts
=> Add preset replace feature

src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/utils.ts, src/structures/game_session.ts, src/structures/guild_preference.ts, src/test/ci/game_utils.test.ts
=> Add unique song counter + reset notification in shuffle unique

.github/workflows/codeql-analysis.yml, src/helpers/management_utils.ts, src/kmq.ts, src/types.ts
=> Dynamically reload end of game messages

src/commands/game_commands/play.ts
=> Make ,vote reminder more prominent on game start message

src/commands/game_commands/vote.ts
=> Account for vote durations greater than 60 minutes, and out-of-sync bonus cache

docs/GAMEPLAY.md, package.json, src/commands/game_commands/hint.ts, src/commands/game_commands/skip.ts, src/helpers/discord_utils.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/test/ci/game_round.test.ts, yarn.lock
=> Add game command to show song/artist name hint

src/structures/game_round.ts
https://medium.com/@nikjohn/regex-test-returns-alternating-results-bd9a1ae42cdd
??????
=> Fix bug with hint generation if two special characters appear in name

src/commands/game_commands/play.ts, src/helpers/discord_utils.ts, src/kmq.ts
Also mention teams mode in ,help play
=> Reload end game messages every 5 minutes

src/scripts/remove-dangling-songs.ts
=> Add script to prune dangling songs

src/structures/game_session.ts
=> Fix bug where timer ignores multiguess delay

docs/GAMEPLAY.md, src/commands/game_commands/play.ts, src/commands/game_options/add.ts, src/commands/game_options/exclude.ts, src/commands/game_options/groups.ts, src/commands/game_options/include.ts, src/commands/game_options/ost.ts, src/commands/game_options/remove.ts, src/helpers/discord_utils.ts
* Replace references of ,includes/,excludes with ,include/,exclude
* Document ,ost exclusive
* Allow use of ,groups/,exclude/,include aliases with ,add/,remove
* Give warning message on ,groups/,include/,exclude ,add/,remove
=> Clarify some documentation, simplify ,add/,remove

package.json, src/config/knexfile_kmq.js, src/database_context.ts, yarn.lock
https://medium.com/epycly/node-js-mysql-driver-benchmarks-2018-86579c402016
=> Switch to mysql2 driver

src/config/knexfile_kmq.js, src/database_context.ts
https://github.com/sidorares/node-mysql2/issues/795
Closes #819
=> Apply workaround for mysql2 casting BIGINT to string

package.json, src/migrations/20210518215005_remove_guild_preference_json.js, yarn.lock
Also removes unneeded template string in a migration
=> Bump ytdl to 4.8.3

src/structures/game_round.ts
=> Fix hint generation to not include removed characters in length calculation

docs/GAMEPLAY.md, src/commands/game_commands/forcehint.ts, src/commands/game_commands/hint.ts
=> Add forcehint command

src/commands/game_commands/begin.ts, src/commands/game_commands/debug.ts, src/commands/game_commands/hint.ts, src/commands/game_commands/play.ts, src/commands/game_commands/skip.ts, src/events/client/messageCreate.ts, src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/helpers/discord_utils.ts, src/structures/game_session.ts
=> Refactor voice channel related commands to use bot's voice channel instead of user

src/commands/game_commands/play.ts, src/events/client/messageCreate.ts, src/helpers/validate.ts
* Add alternative game modes to ,play usage
=> Show command usage in validation error message

src/commands/interfaces/base_command.ts, src/commands/interfaces/ingame_command.ts, src/events/client/messageCreate.ts, src/helpers/validate.ts
* Also allow users to use ,end in ELIMINATION/TEAMS before game starts
=> Fix bug where ,join and ,begin would prevent starting elimination/teams mode

src/commands/game_commands/play.ts, src/commands/game_commands/vote.ts, src/helpers/bot_listing_manager.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/kmq.ts, src/structures/game_session.ts, src/types.ts
Using global state will lead to inconsistencies when moving to clustered solution. Read time from database should also be negligible, entire index should fit in cache
=> Read bonus users from database instead of global state

src/cluster_manager.ts, src/kmq.ts
=> Move bot stats poster to first cluster

src/cluster_manager.ts, src/commands/admin/stats.ts, src/helpers/management_utils.ts, src/kmq.ts, src/migrations/20210724002405_cluster_stats.js
=> Add cluster data table for aggregating cluster stats, fix ,stats

src/commands/admin/reload.ts, src/helpers/management_utils.ts, src/kmq.ts
=> Add cluster/fleet command reloading

src/structures/game_session.ts, src/types.ts
=> Fix race condition between scoreboard population and displayed info

src/events/client/messageCreate.ts, src/helpers/discord_utils.ts
=> Only check for text permissions when needed

package.json, src/cluster_manager.ts, src/events/process/uncaughtException.ts, src/events/process/unhandledRejection.ts, yarn.lock
=> Graceful cluster shutdown

src/commands/game_commands/leaderboard.ts, src/helpers/discord_utils.ts
* Also remove code formatting from leaderboard footer
=> Use formatted number in leaderboard

package.json, src/events/client/guildCreate.ts, src/events/client/guildDelete.ts, src/helpers/management_utils.ts, yarn.lock
Consuming changes listed here: https://github.com/DonovanDMC/eris/blob/everything/README.md
=> Update Eris to consume V9 gateway changes

data/help_strings.json, package.json, src/commands/game_commands/help.ts, src/commands/game_commands/vote.ts, src/commands/game_options/add.ts, src/commands/game_options/groups.ts, src/commands/game_options/remove.ts, src/commands/interfaces/base_command.ts, src/helpers/discord_utils.ts, yarn.lock
- buttons for `,help groups|add|remove`
- buttons for `,help`
- buttons for `,vote`
=> More buttons!!

docker/kmq/Dockerfile
=> No copy data/ in Dockerfile

src/helpers/discord_utils.ts
Reverts Brainicism/KMQ_Discord#907
=> Revert "Add button to YouTube on round end message"

src/helpers/discord_utils.ts
=> Switch to using Discord-branded colors

src/commands/game_options/remove.ts
=> Fix ,remove failing silently when only one group to be removed

src/commands/game_options/remove.ts
=> Support aliases for ,remove

src/events/client/interactionCreate.ts, src/scripts/download-new-songs.ts, src/structures/game_round.ts, src/structures/game_session.ts
* Also fix bug where seed wouldn't get song name
=> Move interaction helpers to GameRound

src/helpers/game_utils.ts
* Removed sets in MC choice generation
=> Case insensitive check when generating multiple choice answers

src/commands/game_commands/forceskip.ts, src/commands/game_commands/skip.ts, src/structures/game_session.ts
=> Fixed bug where multiple choice wouldn't decrement lives or end game in elimination

src/commands/admin/stats.ts, src/fact_generator.ts
=> Use friendlyFormattedNumber in more numbers in facts

package.json, src/events/client/interactionCreate.ts, src/helpers/discord_utils.ts, src/kmq.ts, src/migrations/20210819160851_bookmarked_songs.js, src/structures/game_round.ts, src/structures/game_session.ts, yarn.lock
=> Use Message Commands for bookmarking songs

src/structures/game_session.ts
Empty query error occurs when no bookmarks are stored
=> Only store bookmarks in DB when there are bookmarks

src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/helpers/discord_utils.ts, src/structures/game_session.ts, src/structures/kmq_member.ts
=> Maintain that gameSession owner is in VC

start.sh
Reverts Brainicism/KMQ_Discord#956
=> Revert "Increase Node.js heap size to 2GB"

src/commands/game_commands/begin.ts, src/commands/game_commands/forcehint.ts, src/commands/game_commands/forceskip.ts, src/commands/game_commands/join.ts, src/commands/game_commands/play.ts, src/events/client/messageCreate.ts, src/helpers/discord_utils.ts, src/structures/game_session.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/team_scoreboard.ts
* Fixed bug where end game message shows EXP for teams
* Removed prefix footer reminder on bot ping
=> Mention users instead of using tag

src/cluster_manager.ts, src/helpers/management_utils.ts
=> Fix bug where backups were occuring on all clusters simultaneously

src/commands/game_commands/begin.ts, src/commands/game_commands/forcehint.ts, src/commands/game_commands/forceskip.ts, src/commands/game_commands/hint.ts, src/commands/game_commands/join.ts, src/commands/game_commands/list.ts, src/commands/game_commands/play.ts, src/commands/game_commands/profile.ts, src/commands/game_commands/vote.ts, src/commands/game_options/cutoff.ts, src/commands/game_options/duration.ts, src/commands/game_options/goal.ts, src/events/client/guildCreate.ts, src/events/client/guildDelete.ts, src/helpers/discord_utils.ts, src/helpers/management_utils.ts, src/structures/game_session.ts
=> Standardize embed title capitialization

src/commands/game_commands/profile.ts, src/helpers/discord_utils.ts
=> Add fetchUser to allow uncached profile command calls

src/commands/game_commands/leaderboard.ts, src/helpers/discord_utils.ts, src/helpers/utils.ts, src/structures/game_session.ts, src/test/ci/leaderboard.test.ts
=> Show 'hours/minutes ago' for recent dates, fix timezone inconsistency in date handling

src/structures/game_session.ts
=> Limit multiple choice button labels to 80 characters

src/commands/admin/eval.ts, src/kmq.ts
=> Add eval results for all clusters

package.json, src/structures/game_session.ts, yarn.lock
=> Don't break guess streaks/decrement elimination lives on round error

package.json, yarn.lock
https://github.com/fent/node-ytdl-core/issues/964 
https://github.com/fent/node-ytdl-core/pull/1022
=> Use ytdl-core PR with download speed improvements

src/migrations/20211109064140_dead_links_unique.js, src/scripts/download-new-songs.ts
=> Disallow duplicate vlinks in dead_links table

src/structures/game_round.ts, src/structures/game_session.ts
=> Fix ,answer label overflow on guess count append

src/commands/game_commands/vote.ts, src/helpers/discord_utils.ts, src/helpers/utils.ts
=> Fix minor formatting issues in round end, vote messages

src/commands/admin/forceplay.ts, src/commands/game_commands/preset.ts, src/commands/game_options/add.ts, src/commands/game_options/answer.ts, src/commands/game_options/artisttype.ts, src/commands/game_options/cutoff.ts, src/commands/game_options/duration.ts, src/commands/game_options/exclude.ts, src/commands/game_options/gender.ts, src/commands/game_options/goal.ts, src/commands/game_options/groups.ts, src/commands/game_options/guessmode.ts, src/commands/game_options/include.ts, src/commands/game_options/language.ts, src/commands/game_options/limit.ts, src/commands/game_options/multiguess.ts, src/commands/game_options/ost.ts, src/commands/game_options/release.ts, src/commands/game_options/remove.ts, src/commands/game_options/reset.ts, src/commands/game_options/seek.ts, src/commands/game_options/shuffle.ts, src/commands/game_options/special.ts, src/commands/game_options/subunits.ts, src/commands/game_options/timer.ts, src/helpers/discord_utils.ts, src/structures/guild_preference.ts, src/types.ts
=> Highlight updated/reset options when changed

src/helpers/discord_utils.ts, src/structures/game_session.ts
Closes #1097.
* Fix bug where ,end doesn't send end of round message
=> Reuse song guess message with ,answer

src/fact_generator.ts, src/migrations/20211216025236_song_guess_count_to_song_metadata.js, src/structures/game_round.ts, src/structures/game_session.ts
* Rename `song_guess_count` to `song_metadata`
=> Store per-song skip, hint count, time played, and time to guess

docs/GAMEPLAY.md
* Use invite.kpop.gg for bot invite
=> Use header for server and bot invite links

src/structures/game_round.ts, src/test/ci/game_round.test.ts
Change edit distance requirement based on input length
length <= 4, always fail
4 < length <= 6, distance = 1
length > 6, distance = 2
=> Add variable edit distance requirement for similiarity check

src/structures/song_selector.ts, src/test/ci/song_selector.test.ts
=> Re-add missing call to checkLastPlayedSongs

i18n/ko.json
=> Update Korean File

i18n/ko.json
We worked to match "en.json" and modified some word order.
=> Update ko.json (0.8 Version)

i18n/ko.json
Localize command failure message
=> Update ko.json (0.9.3 Version)

src/structures/player.ts
The field is already an integer in the DB
=> EXP gain as integer

src/helpers/discord_utils.ts, src/structures/elimination_player.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/team.ts, src/structures/team_scoreboard.ts
* Only consider players shown in scoreboard
* Move scoreboard display logic into scoreboard
=> Fixed criteria for switching to larger scoreboard

i18n/en.json, i18n/ko.json, src/commands/game_commands/begin.ts, src/commands/game_commands/play.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/structures/guild_preference.ts
Also fixes a bug where a premium request wasn't correctly determined
=> Wider options message, sent on game start

sql/procedures/create_kmq_data_tables_procedure.sql
=> Deduplicate artist names with first name

docs/GAMEPLAY.md, i18n/en.json, i18n/ko.json, src/commands/game_options/shuffle.ts, src/structures/song_selector.ts, src/test/ci/song_selector.test.ts
=> Add popularity-based shuffle

src/command_prechecks.ts, src/commands/game_commands/debug.ts, src/commands/game_commands/locale.ts, src/commands/game_commands/lookup.ts, src/commands/game_commands/music.ts, src/commands/game_commands/recentlyadded.ts, src/commands/game_commands/skip.ts, src/constants.ts, src/events/client/interactionCreate.ts, src/events/client/messageCreate.ts, src/events/client/voiceChannelJoin.ts, src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/fact_generator.ts, src/helpers/discord_utils.ts, src/helpers/localization_manager.ts, src/state.ts, src/structures/game_session.ts, src/structures/music_session.ts, src/structures/session.ts
#1280 
Reduces warnings from 111 to 76
=> Cyclic dependency cleanup: Remove instanceof calls for Music/GameSession, extract getGuildLocale

src/commands/game_commands/debug.ts, src/commands/game_commands/exp.ts, src/commands/game_commands/forcehint.ts, src/commands/game_commands/forceskip.ts, src/commands/game_commands/join.ts, src/commands/game_commands/leaderboard.ts, src/commands/game_commands/lookup.ts, src/commands/game_commands/play.ts, src/commands/game_commands/profile.ts, src/events/client/interactionCreate.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/utils.ts, src/kmq_client.ts, src/seed/bootstrap.ts, src/seed/seed_db.ts, src/structures/elimination_player.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/structures/kmq_member.ts, src/structures/message_context.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/session.ts, src/types.ts
#1280 
Reduce warnings from 21 to 6
=> Cyclic dependency cleanup: Move getUserTag/getMention, refactor isPremium, other extracted methods

src/commands/admin/forceplay.ts, src/commands/game_commands/music.ts, src/commands/game_commands/options.ts, src/commands/game_commands/play.ts, src/commands/game_commands/preset.ts, src/commands/game_options/add.ts, src/commands/game_options/answer.ts, src/commands/game_options/artisttype.ts, src/commands/game_options/cutoff.ts, src/commands/game_options/duration.ts, src/commands/game_options/exclude.ts, src/commands/game_options/gender.ts, src/commands/game_options/goal.ts, src/commands/game_options/groups.ts, src/commands/game_options/guessmode.ts, src/commands/game_options/include.ts, src/commands/game_options/language.ts, src/commands/game_options/limit.ts, src/commands/game_options/multiguess.ts, src/commands/game_options/ost.ts, src/commands/game_options/release.ts, src/commands/game_options/remove.ts, src/commands/game_options/reset.ts, src/commands/game_options/seek.ts, src/commands/game_options/shuffle.ts, src/commands/game_options/special.ts, src/commands/game_options/subunits.ts, src/commands/game_options/timer.ts, src/events/client/messageCreate.ts, src/helpers/discord_utils.ts
#1280 
Reduces warnings from 6 to 5
=> Cyclic dependency cleanup: Remove dependence on Session in discord_utils

src/commands/game_commands/music.ts, src/commands/game_commands/play.ts, src/helpers/discord_utils.ts, src/structures/game_session.ts, src/structures/music_session.ts, src/structures/session.ts
#1280
Reduces warnings from 4 to 2
=> Cyclic dependency cleanup:: Remove getDebugLogHeader dependence on session

src/seed/bootstrap.ts, src/seed/seed_db.ts
Fixes bug where tables in `kpop_videos` were queried during the downtime during an hourly seed.
```
[ERROR] - game_utils | Error retrieving song count Error: select `id` from `app_kpop_group` where 1 = 0 - Table 'kpop_videos.app_kpop_group' doesn't exist
```
=> Modify seed for atomic kpop_videos database update

src/seed/seed_db.ts
2022-04-18T07:13:59.597Z [ERROR] - Cluster 3 | messageCreate | Error while invoking command (group) | 76367c48-eaf4-43b3-a7ca-bb3855b173cd | {"code":"ER_CANT_AGGREGATE_2COLLATIONS","errno":1267,"sqlState":"HY000","sqlMessage":"Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='","sql":"select `id`, `name` from `app_kpop_group` where `id` in ((select `id` from `app_kpop_group` where `name` in ('cocomelon 😋'))) or `id_artist1` in ((select `id` from `app_kpop_group` where `name` in ('cocomelon 😋'))) or `id_artist2` in ((select `id` from `app_kpop_group` where `name` in ('cocomelon 😋'))) or `id_artist3` in ((select `id` from `app_kpop_group` where `name` in ('cocomelon 😋'))) or `id_artist4` in ((select `id` from `app_kpop_group` where …
=> Update collation of columns with queries sourced by user inputs

i18n/en.json, i18n/ko.json
=> Fix broken goal/elimination conflict message (#1300)

src/commands/game_commands/listen.ts, src/commands/game_commands/play.ts, src/events/client/voiceChannelJoin.ts, src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/structures/game_session.ts, src/structures/listening_session.ts, src/structures/session.ts, src/test/ci/begin.test.ts, src/test/ci/command_prechecks.test.ts, src/test/ci/game_session.test.ts, src/test/ci/game_utils.test.ts, src/test/ci/leaderboard.test.ts, src/test/test_setup.ts
* Unified music and game session isPremium checks
* Replaced broken .some call with Promise
* Ignored duplicate resetPremium calls triggered by command aliases
=> Fix isPremium check (#1302)

src/commands/game_commands/help.ts, src/commands/game_commands/premium.ts
Replaces some comments with early returns as well
=> Hide ,premium from help

src/constants.ts
Closes #1335 
https://ffmpeg.org/ffmpeg-filters.html#areverse
=> Fix 'reverse' special type seeking

package.json, src/helpers/game_utils.ts, src/helpers/patreon_manager.ts, src/kmq_worker.ts, src/state.ts, yarn.lock
=> Replace broken patreon package with http call

i18n/en.json, i18n/ko.json, src/commands/game_commands/news.ts
=> Add message for news command linking to official KMQ server

src/structures/game_session.ts
=> Prevent eliminated players from guessing in MC and elimination game mode

src/commands/game_commands/lookup.ts
* Also removes broken bold on song name
=> Allow lookup via ID or youtube link without https

src/kmq_configuration.ts, src/migrations/20210518215005_remove_guild_preference_json.js, src/seed/bootstrap.ts
Will be used to prevent migrations on canary without us noticing
=> Add feature switch to disallow migrations

sql/procedures/create_kmq_data_tables_procedure.sql
Reduces runtime from 22 seconds to 3 seconds on local
=> Modify name deduplication to use join instead of where in

src/helpers/discord_utils.ts, src/structures/scoreboard.ts
=> Round initiating player's score in scoreboard

i18n/en.json, i18n/ko.json, src/commands/game_options/add.ts, src/commands/game_options/groups.ts, src/commands/game_options/remove.ts, src/helpers/game_utils.ts
=> Add suggested group names when having single unmatched group

src/commands/game_options/add.ts, src/commands/game_options/groups.ts, src/commands/game_options/remove.ts
=> Early return from add/remove if no groups matched

src/helpers/discord_utils.ts, src/interfaces/bookmarked_song.ts, src/migrations/20220605044555_bookmarked_songs_date.js, src/structures/session.ts
- Added date column to `bookmarked_songs`
- Remove unique constraint on ["user_id", "vlink"]. This gives us more information about what song was bookmarked when, for debugging purposes. If we care about unique bookmarks, we can account for that in query
=> Song bookmark improvements

src/commands/game_commands/begin.ts, src/commands/game_commands/join.ts, src/commands/game_commands/play.ts, src/structures/elimination_player.ts, src/structures/game_session.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/team.ts, src/structures/team_scoreboard.ts, src/test/ci/elimination_player.test.ts, src/test/ci/elimination_scoreboard.test.ts, src/test/ci/leaderboard.test.ts, src/test/ci/player.test.ts, src/test/ci/scoreboard.test.ts, src/test/ci/team.test.ts, src/test/ci/team_scoreboard.test.ts
=> Use nicknames for players, various player cleanup

src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/utils.ts, src/structures/player.ts, src/structures/scoreboard.ts, src/structures/team.ts, tsconfig.json
=> Escape formatting chars in names (#1366)

src/commands/game_commands/score.ts, src/constants.ts, src/helpers/discord_utils.ts, src/structures/game_session.ts, src/structures/listening_session.ts, src/structures/scoreboard.ts, src/structures/session.ts, src/test/ci/game_session.test.ts
All of these methods operate on a Session/GameSession
=> Refactor send(Round/Scoreboard/EndGame)Message to (Game)Session

src/commands/game_commands/lookup.ts
Fixes bug where song names that match youtube video ID regex were failing.
=> Lookup fallback to song name if video ID search fails

src/commands/game_commands/lookup.ts
You see, before this change, we had the unfortunate realization that this menu was causing some players discomfort. This is because this specific message was an outlier, which bothered quite a few users. This change will increase player morale, and allow players to focus on the real important part of KMQ, the game.
I'm sorry I didn't test it.
=> fixed the quote issue in lookup.ts

.devcontainer/devcontainer.json, .vscode/i18n-ally-custom-framework.yml, .vscode/settings.json
=> Add support for i18n-ally extension

src/commands/game_commands/premium.ts, src/helpers/game_utils.ts, src/helpers/patreon_manager.ts
* Also use bonus color on ,premium
=> Fix handling no connections of former patron, race condition in awarding premium

src/commands/game_options/add.ts, src/commands/game_options/exclude.ts, src/commands/game_options/groups.ts, src/commands/game_options/include.ts, src/commands/game_options/remove.ts
=> Use button constants instead of hardcoded values

i18n/en.json, i18n/ko.json, src/commands/admin/stats.ts, src/commands/game_commands/exp.ts, src/commands/game_commands/hint.ts, src/commands/game_commands/listen.ts, src/commands/game_commands/options.ts, src/commands/game_commands/play.ts, src/commands/game_commands/skip.ts, src/commands/game_commands/vote.ts, src/commands/game_options/answer.ts, src/commands/game_options/artisttype.ts, src/commands/game_options/groups.ts, src/commands/game_options/guessmode.ts, src/commands/game_options/language.ts, src/commands/game_options/multiguess.ts, src/commands/game_options/ost.ts, src/commands/game_options/release.ts, src/commands/game_options/reset.ts, src/commands/game_options/seek.ts, src/commands/game_options/shuffle.ts, src/commands/game_options/special.ts, src/commands/game_options/subunits.ts, src/events/client/messageCreate.ts, src/helpers/discord_utils.ts, src/structures/session.ts
Use `tryCreateInteractionCustomPayloadAcknowledgement()` instead of retrofitted success/error ack functions. Bold embed titles by default
Closes #1426
=> Add tryCreateInteractionCustomPayloadAcknowledgement function

src/commands/admin/appcommands.ts
- Consolidate dev/prod reload/delete
- Make deletion sequential
- Show which calls (potentially) failed
=> Application commands reload/delete refactor

package.json, src/helpers/discord_utils.ts, yarn.lock
https://github.com/Brainicism/eris-pagination/pull/5
=> Remove message requirement in eris-pagination

src/structures/session.ts
~~TODO: find other places where boldTitle impacted embed titles~~
=> Remove double bold in song message

src/events/client/messageCreate.ts
```
./error-2022-09-03.log:2022-09-03T17:18:36.122Z [ERROR] - messageCreate | Error while invoking command (help) | dca58677-938c-4d0c-8962-a590275938aa | Error: [object Object]
./combined-2022-09-03.log:2022-09-03T17:18:36.122Z [ERROR] - messageCreate | Error while invoking command (help) | dca58677-938c-4d0c-8962-a590275938aa | Error: [object Object]
./combined-2022-08-24.log:2022-08-24T04:31:46.864Z [ERROR] - messageCreate | Error while invoking command (stop) | e79daa58-67c1-4abf-b24a-0fd532b7840b | Error: Request timed out (>15000ms)
./error-2022-09-04.log:2022-09-04T00:01:42.996Z [ERROR] - messageCreate | Error while invoking command (help) | 887d2218-ec22-401e-ab9a-0bdeb73f7bbf | Error: [object Object]
./error-2022-09-04.log:2022-09-04T00:01:46.162Z [ERROR] - messageCreate | Error …
```
=> Stringify messageCreate error

src/commands/game_commands/score.ts, src/structures/game_session.ts
~~Blocked by ,lookup's pagination changes~~
=> Slash command for ,score

src/seed/seed_db.ts, src/test/ci/game_utils.test.ts, src/test/test_setup.ts
Daisuki db export no longer contains `REMOVE THIS LINE TO USE` at the start
=> Remove Daisuki first line check

src/events/client/warn.ts
The typings say string but the code emits string | Error
=> Fix warning log if emitted object is an Error

src/helpers/spotify_manager.ts, src/structures/song_selector.ts
Reduces playlist fetch time from 9.1s -> 1s on 4k song playlist
=> Parallelize Spotify playlist fetch

docs/GAMEPLAY.md, i18n/en.json, i18n/ko.json, src/commands/game_commands/feedback.ts, src/events/client/interactionCreate.ts
=> Add command for feedback submission via modal

src/seed/bootstrap.ts
Reduces backup size from 261MB to 156MB
=> Clean up stale system stats data

package.json, src/scripts/backup-kmq-database.ts
Alpine's `tar` binary doesn't support `--remove-files`
=> Manually remove sql dump after compressing

package.json, yarn.lock
https://github.com/fent/node-ytdl-core/issues/1197
=> Apply patch to fix ytdl downloads

i18n/en.json, i18n/ko.json, src/commands/game_commands/lookup.ts
=> Show whether song is premium-only in /lookup

i18n/en.json, i18n/ko.json, src/commands/game_commands/leaderboard.ts
=> Show when the leaderboard was reset and will be reset

src/helpers/discord_utils.ts, src/helpers/utils.ts, src/structures/game_session.ts, src/types.ts
=> Slash commands in /options are clickable

src/commands/game_commands/leaderboard.ts, src/test/ci/leaderboard.test.ts
=> Add indicator for leaderboard command invoker

src/helpers/discord_utils.ts
* Index directly by locale in gameInfoMessage
=> Fix bug where zh-CN and es-ES weren't indexed in gameInfoMessage

src/commands/game_commands/profile.ts, src/commands/game_options/spotify.ts, src/helpers/discord_utils.ts, src/helpers/spotify_manager.ts, src/helpers/utils.ts, src/structures/song_selector.ts
* Also increases playlist parse time from 15s to 30s
=> Add progress bar for /spotify and /profile

src/commands/game_commands/exp.ts, src/constants.ts, src/helpers/utils.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/test/ci/game_round.test.ts
=> Send lightning emoji on quick guess

docker/kmq/Dockerfile
=> Add text editing utils to Docker image

package.json, yarn.lock
https://github.com/fent/node-ytdl-core/issues/1250
=> Temporarily patch ytdl-core

src/structures/game_session.ts
=> Fix bug where songs guessed was incremented by score

sql/procedures/post_seed_data_cleaning_procedure.sql
Caused empty brackets in names
=> Skip artist name dedup for artists without first name

package.json, yarn.lock
The latest release fixes the failed first download
=> Update distubejs/ytdl-core to 4.13.3

i18n/en.json, i18n/es-ES.json, i18n/fr.json, i18n/ja.json, i18n/ko.json, i18n/zh-CN.json, src/commands/game_commands/list.ts, src/commands/game_options/spotify.ts, src/fact_generator.ts, src/helpers/spotify_manager.ts, src/interfaces/matched_playlist.ts, src/structures/song_selector.ts
=> Add /spotify matches to see matched/unmatched songs

src/commands/game_commands/play.ts, src/commands/game_commands/preset.ts, src/events/client/interactionCreate.ts, src/structures/team_scoreboard.ts
Closes https://github.com/Brainicism/KMQ_Discord/issues/1782
=> Autocomplete team names with /play teams join

i18n/en.json, i18n/es-ES.json, i18n/fr.json, i18n/ja.json, i18n/ko.json, i18n/zh-CN.json, src/commands/game_commands/join.ts, src/commands/game_commands/play.ts
Closes https://github.com/Brainicism/KMQ_Discord/issues/1783
=> Replace /play teams instructions with clickable slash commands

src/commands/game_options/spotify.ts
* Fix bug where /spotify slash command wasn't responding
* Fix bug where /spotify matches wasn't responding when playlist uncached
=> Spotify command interaction bug fixes

src/commands/game_commands/end.ts, src/commands/game_commands/play.ts, src/events/client/guildDelete.ts, src/events/client/messageCreate.ts, src/events/client/voiceChannelLeave.ts, src/events/client/voiceChannelSwitch.ts, src/helpers/game_utils.ts, src/kmq_worker.ts, src/migrations/2023-12-28T02:13:10.987Z-player-stats-last-game-error.ts, src/scripts/prepare-kysely-schema.sh, src/structures/game_session.ts, src/structures/listening_session.ts, src/structures/session.ts, src/test/ci/game_session.test.ts, src/typings/kmq_db.d.ts
=> Don't consume first game of day bonus when session ends erroneously

src/seed/migrate_down.ts
=> Add interactive CLI tool for migrate down

src/helpers/management_utils.ts
Reverts Brainicism/KMQ_Discord#1801
=> Revert "Only send news on first cluster"

src/helpers/management_utils.ts
* Also replaces the early return in hourly job
=> Fix reloading news

src/helpers/reddit_client.ts
* Single quotes don't work for multiple flair exclusion
=> Fix filtering by flair

src/helpers/reddit_client.ts
Helps differentiate between:
* News or rumors
* Album or MV releases
Example prompt:
```
2024-01-05 | teaser:teaser | SISTAR19 - NO MORE (MA BOY) (Concept Photo 1)
2024-01-03 | news:news | EXO's Baekhyun Sets Up His Own Agency, Recruits Chen And Xiumin
2024-01-02 | news:rumor | BLACKPINK's Jisoo Will Reportedly Join Her Brother's Company For Solo Activities
2024-01-07 | teaser:teaser | (G)I-DLE - The 2nd Full Album: [2] (Comeback Teaser Image)
2024-01-08 | release:mv | ITZY - UNTOUCHABLE
2024-01-07 | teaser:teaser | SISTAR19 - NO MORE (MA BOY) (Concept Photo 2)
2024-01-04 | news:news | Girls' Generation's Yoona Renews Contract With SM Entertainment For A 3rd Time
2024-01-07 | news:news | All 8 members of EXO will continue their group activities as EXO through SM Entertainment. Individual …
```
=> Add both r/kpop flairs to prompt

src/commands/misc_commands/news.ts, src/helpers/gemini_client.ts, src/helpers/management_utils.ts, src/interfaces/news_summary.ts, src/kmq_service.ts, src/kmq_worker.ts, src/state.ts
Prevents duplicate work by each cluster
=> Generate news in kmq_service

package.json, src/environment.d.ts, src/kmq_service.ts, src/kmq_worker.ts, start.sh
For faster iterations
- skips bootstrap
- doesn't hydrate caches on startup
=> Add dev_minimal npm target

i18n/en.json, i18n/es-ES.json, i18n/fr.json, i18n/ja.json, i18n/ko.json, i18n/zh-CN.json, src/commands/game_commands/profile.ts, src/migrations/2024-01-23T02:05:56.446Z-player-stat-ineligible-rank.ts, src/typings/kmq_db.d.ts
=> Add rank ineligibility

src/helpers/gemini_client.ts, src/helpers/reddit_client.ts, src/kmq_service.ts
* Also converts reddit top post failure to warning from error
=> Fetch news per-range instead of per-locale-range

src/helpers/management_utils.ts
=> Bonus artist collab fix

src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/test/ci/game_utils.test.ts
Removed collabs and artists without songs from filters. Closes #1519
=> Removed collabs and artists without songs from filters

src/scripts/announce-restart.ts
=> Upgrade rollback on timed out provisioning

src/structures/guild_preference.ts
=> Persist removed extraneous game options from GuildPreference

src/structures/song_selector.ts
Forceplay should have higher priority than spotify
=> Fix forceplay when Spotify option is checked

package.json, yarn.lock
Adds in newlines at the end of the file
=> Update i18n-ai-translate to 1.2.1

src/helpers/utils.ts, src/structures/game_round.ts
=> Skip string cleaning for purely non-alphanumeric strings

src/helpers/game_utils.ts, src/migrations/2024-02-22T00:34:49.756Z-last-game-started.ts, src/structures/game_session.ts, src/typings/kmq_db.d.ts
=> Calculate FGOTD bonus with last session create time

src/structures/game_session.ts
Same EXP curve from 0<x<=10000, growing tangentially linearly to (40000,3000)
=> Update EXP curve

.github/workflows/gci-e2e.yml, src/helpers/management_utils.ts, src/kmq_worker.ts
=> Check GCI E2E run for errors

.devcontainer/devcontainer.json, docker/kmq/Dockerfile
- Remove azcopy
- Remove removal of dev dependencies, improves layer caching
=> Dockerfile changes

src/commands/game_commands/lookup.ts
=> Fix bug where autocomplete didn't show English results when Korean locale

src/helpers/reddit_client.ts
=> Filter AMAs from /news

sql/procedures/create_kmq_data_tables_procedure.sql
=> Atomically update app_kpop_groups to avoid race condition

src/helpers/utils.ts
`typeof null` is `object` apparently
=> Fix song selection bug due to forcePlayID

src/commands/admin/debug.ts, src/commands/game_commands/exp.ts, src/commands/game_commands/lookup.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/interfaces/matched_playlist.ts, src/structures/game_session.ts, src/structures/session.ts, src/structures/song_selector.ts, src/test/ci/exp.test.ts, src/test/ci/song_selector.test.ts
Also refactor `getAvailableSongCount` to use SongSelector.
=> Mark songs as ineligible for base EXP for duplicate aliases

src/helpers/utils.ts
Apparently typeof array = object
=> Fix song selection bug due to Array serialization

src/commands/game_commands/lookup.ts, src/structures/song_selector.ts, src/test/ci/song_selector.test.ts
Also fix shadowbanned artist test
=> Remove static methods from SongSelector

src/helpers/playlist_manager.ts
=> Spotify match prioritize closest artist name when multiple due to punctuation

src/constants.ts, src/events/client/guildCreate.ts
https://discord.com/developers/docs/reference#locales
=> Add missing languages to mapping between Discord preferred locales and locale

src/commands/game_commands/forcehint.ts, src/commands/game_commands/hint.ts, src/commands/game_commands/lookup.ts, src/helpers/discord_utils.ts, src/helpers/game_utils.ts, src/helpers/management_utils.ts, src/helpers/playlist_manager.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/structures/song_selector.ts
- Extract `generateHint` and `getTimeToGuessMs` into GameRound
- Move floating variables into GameRound class
=> GameRound refactoring

src/structures/game_session.ts, src/test/end-to-end-tests/test-runner-bot.ts, src/test/end-to-end-tests/test_suites/gameplay_test.ts, src/test/end-to-end-tests/test_suites/test_suite.ts
- Don't persist game session stats for test-runner
- Add vc polling to check if test-runner can run
=> Test runner changes

sql/procedures/create_kmq_data_tables_procedure.sql, src/constants.ts, src/enums/option_types/release_type.ts, src/scripts/download-new-songs.ts, src/structures/song_selector.ts
Also remove undesirable songs based on tags during `available_songs` creation instead of during song selection.
=> Add option for /release bside

.github/workflows/gci-e2e.yml
Bootstrap may silently fail due to 429s during download
=> Check available_songs count after bootstrap

src/env_variable_manager.ts, src/environment.d.ts, src/kmq_service.ts, src/kmq_worker.ts, src/seed/bootstrap.ts, src/structures/session.ts, src/structures/song_selector.ts
=> Add god mode for having every song available

src/structures/song_selector.ts
=> Only print ineligible aliases

src/constants.ts, src/helpers/discord_utils.ts, src/kmq.ts, src/seed/seed_db.ts, src/test/end-to-end-tests/test-runner-bot.ts
File uploads are not previewable on mobile. Prefer embeds until length limit is reached
=> Songs changed webhook prefer message over file

src/helpers/game_utils.ts, src/structures/game_session.ts
- Also use built in sql RAND() instead of lodash sample()
- Fix bug where /guessmode artist could have duplicate answers
=> Select songs similar in popularity for `/answer hard`

src/helpers/discord_utils.ts, src/kmq.ts
```
2024-04-03T17:42:49.542Z [ERROR] - discord_utils | Error sending message. Unknown error. textChannelID = 696257712165748818. err = Error: Request timed out (>15000ms) on POST /channels/696257712165748818/messages 
```
=> Handle request timeout in sendMessageExceptionHandler

i18n/de.json, i18n/en.json, i18n/es-ES.json, i18n/fr.json, i18n/hi.json, i18n/id.json, i18n/ja.json, i18n/ko.json, i18n/nl.json, i18n/pt-BR.json, i18n/ru.json, i18n/zh-CN.json, src/commands/game_commands/lookup.ts
=> Add guess rate to /lookup

sql/procedures/create_kmq_data_tables_procedure.sql, sql/procedures/generate_expected_available_songs_procedure.sql, src/seed/seed_db.ts, src/typings/kmq_db.d.ts
Current method is sensitive to song name changes
=> Identify added/removed songs by daisuki song id

src/structures/game_session.ts
No longer necessary since no New Clip button
=> Remove clip guess message

src/structures/session.ts
=> Skip and bookmark buttons as secondary style

src/constants.ts, src/structures/game_round.ts, src/structures/game_session.ts, src/structures/guild_preference.ts, src/structures/listening_round.ts, src/structures/listening_session.ts, src/structures/round.ts, src/structures/session.ts
=> Refactor skip button to show in multiple choice

src/helpers/playlist_manager.ts
Bugfix accidentally removed in https://github.com/Brainicism/KMQ_Discord/pull/2098
=> Readd bugfix for where podcasts prevented parsing Spotify playlist

src/commands/misc_commands/lookup.ts, src/events/client/interactionCreate.ts
* `/lookup song_name` and `/lookup song_link` are just `song` and `link` respectively
* Move lookup to `misc_commands`
=> Simplify lookup slash command scoping

src/commands/admin/stats.ts, src/kmq_worker.ts, src/state.ts, src/structures/game_session.ts
=> Add running stats

package.json, yarn.lock
JSON processing is now faster than erlpack for given discord payloads
=> Remove erlpack

src/scripts/announce-restart.sh
Polling until restart_date already happens in `announce_restart()`
=> Remove extraneous sleep in announce-restart

package.json, src/constants.ts, src/structures/session.ts, yarn.lock
=> Set voice channel status to KMQ emoji

src/structures/game_session.ts
The values are initialized to 0 which is falsy.
=> Fix null check on interactionIncorrectAnswerUUIDs

src/scripts/download-new-songs.ts
Youtube bot detection returns 403s, don't consider them dead links.
=> Exclude 403s from dead_links

src/scripts/download-new-songs.ts, src/seed/seed_db.ts
Check for mp3 files that weren't ffmpeg encoded through KMQ. Either because a seed was abruptly ended, or it was downloaded outside of KMQ.
=> Add support for encoding externally downloaded mp3s

src/scripts/download-new-songs.ts
Extracts this part of the stderr output
```
ERROR: [youtube] B1xWdZA95Nc: Video unavailable
```
=> Re-introduce dead_links on download fail

src/helpers/management_utils.ts
We are firing 50 messages at the exact same time, the discord rate limit is 60/s
=> Synchronous news sending

src/helpers/kmq_song_downloader.ts
--abort-on-unavailable-fragments
Abort download if a fragment is unavailable
=> Add --abort-on-unavailable-fragments flag to yt-dlp

.github/workflows/gci-e2e.yml, package.json, src/constants.ts, src/helpers/kmq_song_downloader.ts, src/scripts/generate-yt-session-bgutils.ts, src/scripts/session-generator.sh, yarn.lock
Generate PO token without dependency on docker
=> Generate youtube session via bg-utils

src/helpers/kmq_song_downloader.ts, src/kmq_configuration.ts
PO token usage might prevent proxies from being blacklisted (?)
=> Allow mixed use of PO tokens and proxy

package.json, src/structures/session.ts, yarn.lock
https://github.com/Brainicism/eris/pull/16
=> Apply seek before audio encoding

src/seed/seed_db.ts, src/test/unit_tests/test_setup.ts
=> Set default charset for loading stored procs

src/structures/game_round.ts, src/structures/queried_song.ts, src/structures/song_selector.ts, src/test/unit_tests/ci/exp.test.ts, src/test/unit_tests/ci/game_round.test.ts
`clean_song_name_alpha_numeric` replaces accented letters with non-accented, so that we don't need to rely on aliases on daisuki for that
=> Add clean song name as accepted song answer

docker/kmq/Dockerfile
20.04 LTS support ending in May 2025
=> Update to Ubuntu 22

package.json, yarn.lock
https://github.com/Brainicism/eris/commit/452a2c9046b765280c6238d449afc716ee983305
=> Update Eris to support new gateway and encryption modes
